// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_test_bool_cabi<T: Guest>(arg0: i32) -> i32 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::test_bool(_rt::bool_lift(arg0 as u8));
    match result0 {
        true => 1,
        false => 0,
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_test_s32_cabi<T: Guest>(arg0: i32) -> i32 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::test_s32(arg0);
    _rt::as_i32(result0)
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_test_s64_cabi<T: Guest>(arg0: i64) -> i64 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::test_s64(arg0);
    _rt::as_i64(result0)
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_test_float64_cabi<T: Guest>(arg0: f64) -> f64 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::test_float64(arg0);
    _rt::as_f64(result0)
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_test_char_cabi<T: Guest>(arg0: i32) -> i32 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::test_char(_rt::char_lift(arg0 as u32));
    _rt::as_i32(result0)
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_test_string_cabi<T: Guest>(arg0: *mut u8, arg1: usize) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let result1 = T::test_string(_rt::string_lift(bytes0));
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec3 = (result1.into_bytes()).into_boxed_slice();
    let ptr3 = vec3.as_ptr().cast::<u8>();
    let len3 = vec3.len();
    ::core::mem::forget(vec3);
    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
    *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_test_string<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    _rt::cabi_dealloc(l0, l1, 1);
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_test_multi_params_cabi<T: Guest>(arg0: i32, arg1: i32) -> i32 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::test_multi_params(arg0, arg1);
    _rt::as_i32(result0)
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_test_multi_returns_cabi<T: Guest>(arg0: i32) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::test_multi_returns(arg0);
    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
    let (t2_0, t2_1) = result0;
    *ptr1.add(0).cast::<i32>() = _rt::as_i32(t2_0);
    *ptr1.add(4).cast::<i32>() = _rt::as_i32(t2_1);
    ptr1
}
pub trait Guest {
    fn test_bool(input: bool) -> bool;
    fn test_s32(input: i32) -> i32;
    fn test_s64(input: i64) -> i64;
    fn test_float64(input: f64) -> f64;
    fn test_char(input: char) -> char;
    fn test_string(input: _rt::String) -> _rt::String;
    fn test_multi_params(a: i32, b: i32) -> i32;
    fn test_multi_returns(input: i32) -> (i32, i32);
}
#[doc(hidden)]
macro_rules! __export_world_basic_types_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "test-bool")] unsafe extern "C" fn
        export_test_bool(arg0 : i32,) -> i32 { unsafe { $($path_to_types)*::
        _export_test_bool_cabi::<$ty > (arg0) } } #[unsafe (export_name = "test-s32")]
        unsafe extern "C" fn export_test_s32(arg0 : i32,) -> i32 { unsafe {
        $($path_to_types)*:: _export_test_s32_cabi::<$ty > (arg0) } } #[unsafe
        (export_name = "test-s64")] unsafe extern "C" fn export_test_s64(arg0 : i64,) ->
        i64 { unsafe { $($path_to_types)*:: _export_test_s64_cabi::<$ty > (arg0) } }
        #[unsafe (export_name = "test-float64")] unsafe extern "C" fn
        export_test_float64(arg0 : f64,) -> f64 { unsafe { $($path_to_types)*::
        _export_test_float64_cabi::<$ty > (arg0) } } #[unsafe (export_name =
        "test-char")] unsafe extern "C" fn export_test_char(arg0 : i32,) -> i32 { unsafe
        { $($path_to_types)*:: _export_test_char_cabi::<$ty > (arg0) } } #[unsafe
        (export_name = "test-string")] unsafe extern "C" fn export_test_string(arg0 : *
        mut u8, arg1 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
        _export_test_string_cabi::<$ty > (arg0, arg1) } } #[unsafe (export_name =
        "cabi_post_test-string")] unsafe extern "C" fn _post_return_test_string(arg0 : *
        mut u8,) { unsafe { $($path_to_types)*:: __post_return_test_string::<$ty > (arg0)
        } } #[unsafe (export_name = "test-multi-params")] unsafe extern "C" fn
        export_test_multi_params(arg0 : i32, arg1 : i32,) -> i32 { unsafe {
        $($path_to_types)*:: _export_test_multi_params_cabi::<$ty > (arg0, arg1) } }
        #[unsafe (export_name = "test-multi-returns")] unsafe extern "C" fn
        export_test_multi_returns(arg0 : i32,) -> * mut u8 { unsafe {
        $($path_to_types)*:: _export_test_multi_returns_cabi::<$ty > (arg0) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_basic_types_cabi;
#[cfg_attr(target_pointer_width = "64", repr(align(8)))]
#[cfg_attr(target_pointer_width = "32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit<u8>; 2 * ::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea(
    [::core::mem::MaybeUninit::uninit(); 2 * ::core::mem::size_of::<*const u8>()],
);
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    pub fn as_f64<T: AsF64>(t: T) -> f64 {
        t.as_f64()
    }
    pub trait AsF64 {
        fn as_f64(self) -> f64;
    }
    impl<'a, T: Copy + AsF64> AsF64 for &'a T {
        fn as_f64(self) -> f64 {
            (*self).as_f64()
        }
    }
    impl AsF64 for f64 {
        #[inline]
        fn as_f64(self) -> f64 {
            self as f64
        }
    }
    pub unsafe fn char_lift(val: u32) -> char {
        if cfg!(debug_assertions) {
            core::char::from_u32(val).unwrap()
        } else {
            core::char::from_u32_unchecked(val)
        }
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub use alloc_crate::string::String;
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_basic_types_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_basic_types_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_basic_types_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:wasmtime4j:test@0.1.0:basic-types:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 406] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x94\x02\x01A\x02\x01\
A\x11\x01@\x01\x05input\x7f\0\x7f\x04\0\x09test-bool\x01\0\x01@\x01\x05inputz\0z\
\x04\0\x08test-s32\x01\x01\x01@\x01\x05inputx\0x\x04\0\x08test-s64\x01\x02\x01@\x01\
\x05inputu\0u\x04\0\x0ctest-float64\x01\x03\x01@\x01\x05inputt\0t\x04\0\x09test-\
char\x01\x04\x01@\x01\x05inputs\0s\x04\0\x0btest-string\x01\x05\x01@\x02\x01az\x01\
bz\0z\x04\0\x11test-multi-params\x01\x06\x01o\x02zz\x01@\x01\x05inputz\0\x07\x04\
\0\x12test-multi-returns\x01\x08\x04\0!wasmtime4j:test/basic-types@0.1.0\x04\0\x0b\
\x11\x01\0\x0bbasic-types\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit\
-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
