/*
 * Copyright 2025 Tegmentum AI
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ai.tegmentum.wasmtime4j.wasi;

/**
 * WASI Preview 2 Random interface.
 *
 * <p>Provides access to cryptographically secure random number generation. The random bytes
 * generated are suitable for cryptographic purposes.
 *
 * <p>This interface maps to the wasi:random/random@0.2.0 WIT interface.
 *
 * <p>Example usage:
 *
 * <pre>{@code
 * WasiRandom random = runtime.getRandom();
 *
 * // Get 32 random bytes for a key
 * byte[] key = random.getRandomBytes(32);
 *
 * // Get a random 64-bit value
 * long randomValue = random.getRandomU64();
 * }</pre>
 *
 * @since 1.0.0
 */
public interface WasiRandom {

  /**
   * Generates cryptographically secure random bytes.
   *
   * <p>The generated bytes are suitable for use as cryptographic keys, nonces, or other
   * security-sensitive purposes.
   *
   * @param length the number of random bytes to generate
   * @return a byte array containing the random bytes
   * @throws IllegalArgumentException if length is negative
   */
  byte[] getRandomBytes(int length);

  /**
   * Generates a cryptographically secure random 64-bit unsigned integer.
   *
   * <p>The returned value is uniformly distributed across the full range of 64-bit values. Since
   * Java does not have unsigned types, the value is returned as a signed long.
   *
   * @return a random 64-bit value
   */
  long getRandomU64();

  /**
   * Fills the provided byte array with cryptographically secure random bytes.
   *
   * <p>This method modifies the input array in place, filling it with random bytes.
   *
   * @param buffer the byte array to fill with random bytes
   * @throws IllegalArgumentException if buffer is null
   */
  default void fillRandomBytes(final byte[] buffer) {
    if (buffer == null) {
      throw new IllegalArgumentException("Buffer cannot be null");
    }
    byte[] random = getRandomBytes(buffer.length);
    System.arraycopy(random, 0, buffer, 0, buffer.length);
  }
}
