/*
 * Copyright 2025 Tegmentum AI
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ai.tegmentum.wasmtime4j.config;

/**
 * Interface for providing a custom compilation cache backend for Wasmtime's incremental
 * compilation.
 *
 * <p>When enabled via {@link EngineConfig#enableIncrementalCompilation(CacheStore)}, Wasmtime will
 * use this store to cache compiled artifacts across compilations. This can significantly speed up
 * repeated compilations of the same or similar WebAssembly modules.
 *
 * <p>Implementations must be thread-safe since Wasmtime may call {@code get} and {@code insert}
 * from multiple threads concurrently.
 *
 * <p>Example usage with an in-memory cache:
 *
 * <pre>{@code
 * ConcurrentHashMap<ByteBuffer, byte[]> cache = new ConcurrentHashMap<>();
 * CacheStore store = new CacheStore() {
 *     public byte[] get(byte[] key) {
 *         return cache.get(ByteBuffer.wrap(key));
 *     }
 *     public boolean insert(byte[] key, byte[] value) {
 *         cache.put(ByteBuffer.wrap(key), value);
 *         return true;
 *     }
 * };
 *
 * EngineConfig config = new EngineConfig();
 * config.enableIncrementalCompilation(store);
 * Engine engine = Engine.create(config);
 * }</pre>
 *
 * @since 1.0.0
 */
public interface CacheStore {

  /**
   * Retrieves a cached compilation artifact for the given key.
   *
   * <p>This method is called by Wasmtime during module compilation to check if a previously
   * compiled artifact is available in the cache.
   *
   * @param key the cache key (opaque byte array generated by Wasmtime)
   * @return the cached artifact bytes, or {@code null} if no entry exists for the key
   */
  byte[] get(byte[] key);

  /**
   * Stores a compilation artifact in the cache.
   *
   * <p>This method is called by Wasmtime after compiling a module (or part of a module) to store
   * the result for future use.
   *
   * @param key the cache key (opaque byte array generated by Wasmtime)
   * @param value the compiled artifact bytes to cache
   * @return {@code true} if the insertion succeeded, {@code false} if it failed (e.g., cache full)
   */
  boolean insert(byte[] key, byte[] value);
}
