// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[derive(Clone)]
pub struct Person {
    pub name: _rt::String,
    pub age: u32,
    pub email: _rt::String,
}
impl ::core::fmt::Debug for Person {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Person")
            .field("name", &self.name)
            .field("age", &self.age)
            .field("email", &self.email)
            .finish()
    }
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct Point {
    pub x: f64,
    pub y: f64,
}
impl ::core::fmt::Debug for Point {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Point").field("x", &self.x).field("y", &self.y).finish()
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_echo_person_cabi<T: Guest>(
    arg0: *mut u8,
    arg1: usize,
    arg2: i32,
    arg3: *mut u8,
    arg4: usize,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let len1 = arg4;
    let bytes1 = _rt::Vec::from_raw_parts(arg3.cast(), len1, len1);
    let result2 = T::echo_person(Person {
        name: _rt::string_lift(bytes0),
        age: arg2 as u32,
        email: _rt::string_lift(bytes1),
    });
    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
    let Person { name: name4, age: age4, email: email4 } = result2;
    let vec5 = (name4.into_bytes()).into_boxed_slice();
    let ptr5 = vec5.as_ptr().cast::<u8>();
    let len5 = vec5.len();
    ::core::mem::forget(vec5);
    *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
    *ptr3.add(0).cast::<*mut u8>() = ptr5.cast_mut();
    *ptr3.add(2 * ::core::mem::size_of::<*const u8>()).cast::<i32>() = _rt::as_i32(age4);
    let vec6 = (email4.into_bytes()).into_boxed_slice();
    let ptr6 = vec6.as_ptr().cast::<u8>();
    let len6 = vec6.len();
    ::core::mem::forget(vec6);
    *ptr3.add(4 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
    *ptr3.add(3 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr6
        .cast_mut();
    ptr3
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_echo_person<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    _rt::cabi_dealloc(l0, l1, 1);
    let l2 = *arg0.add(3 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l3 = *arg0.add(4 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
    _rt::cabi_dealloc(l2, l3, 1);
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_echo_point_cabi<T: Guest>(arg0: f64, arg1: f64) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::echo_point(Point { x: arg0, y: arg1 });
    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
    let Point { x: x2, y: y2 } = result0;
    *ptr1.add(0).cast::<f64>() = _rt::as_f64(x2);
    *ptr1.add(8).cast::<f64>() = _rt::as_f64(y2);
    ptr1
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_create_person_cabi<T: Guest>(
    arg0: *mut u8,
    arg1: usize,
    arg2: i32,
    arg3: *mut u8,
    arg4: usize,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let len1 = arg4;
    let bytes1 = _rt::Vec::from_raw_parts(arg3.cast(), len1, len1);
    let result2 = T::create_person(
        _rt::string_lift(bytes0),
        arg2 as u32,
        _rt::string_lift(bytes1),
    );
    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
    let Person { name: name4, age: age4, email: email4 } = result2;
    let vec5 = (name4.into_bytes()).into_boxed_slice();
    let ptr5 = vec5.as_ptr().cast::<u8>();
    let len5 = vec5.len();
    ::core::mem::forget(vec5);
    *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
    *ptr3.add(0).cast::<*mut u8>() = ptr5.cast_mut();
    *ptr3.add(2 * ::core::mem::size_of::<*const u8>()).cast::<i32>() = _rt::as_i32(age4);
    let vec6 = (email4.into_bytes()).into_boxed_slice();
    let ptr6 = vec6.as_ptr().cast::<u8>();
    let len6 = vec6.len();
    ::core::mem::forget(vec6);
    *ptr3.add(4 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
    *ptr3.add(3 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr6
        .cast_mut();
    ptr3
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_create_person<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    _rt::cabi_dealloc(l0, l1, 1);
    let l2 = *arg0.add(3 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l3 = *arg0.add(4 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
    _rt::cabi_dealloc(l2, l3, 1);
}
pub trait Guest {
    fn echo_person(p: Person) -> Person;
    fn echo_point(p: Point) -> Point;
    fn create_person(name: _rt::String, age: u32, email: _rt::String) -> Person;
}
#[doc(hidden)]
macro_rules! __export_world_with_records_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "echo-person")] unsafe extern "C" fn
        export_echo_person(arg0 : * mut u8, arg1 : usize, arg2 : i32, arg3 : * mut u8,
        arg4 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
        _export_echo_person_cabi::<$ty > (arg0, arg1, arg2, arg3, arg4) } } #[unsafe
        (export_name = "cabi_post_echo-person")] unsafe extern "C" fn
        _post_return_echo_person(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_echo_person::<$ty > (arg0) } } #[unsafe (export_name =
        "echo-point")] unsafe extern "C" fn export_echo_point(arg0 : f64, arg1 : f64,) ->
        * mut u8 { unsafe { $($path_to_types)*:: _export_echo_point_cabi::<$ty > (arg0,
        arg1) } } #[unsafe (export_name = "create-person")] unsafe extern "C" fn
        export_create_person(arg0 : * mut u8, arg1 : usize, arg2 : i32, arg3 : * mut u8,
        arg4 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
        _export_create_person_cabi::<$ty > (arg0, arg1, arg2, arg3, arg4) } } #[unsafe
        (export_name = "cabi_post_create-person")] unsafe extern "C" fn
        _post_return_create_person(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_create_person::<$ty > (arg0) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_with_records_cabi;
#[repr(align(8))]
struct _RetArea([::core::mem::MaybeUninit<u8>; 5 * ::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea(
    [::core::mem::MaybeUninit::uninit(); 5 * ::core::mem::size_of::<*const u8>()],
);
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub fn as_f64<T: AsF64>(t: T) -> f64 {
        t.as_f64()
    }
    pub trait AsF64 {
        fn as_f64(self) -> f64;
    }
    impl<'a, T: Copy + AsF64> AsF64 for &'a T {
        fn as_f64(self) -> f64 {
            (*self).as_f64()
        }
    }
    impl AsF64 for f64 {
        #[inline]
        fn as_f64(self) -> f64 {
            self as f64
        }
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_with_records_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_with_records_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_with_records_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:wasmtime4j:records@0.1.0:with-records:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 320] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xbd\x01\x01A\x02\x01\
A\x0a\x01r\x03\x04names\x03agey\x05emails\x03\0\x06person\x03\0\0\x01r\x02\x01xu\
\x01yu\x03\0\x05point\x03\0\x02\x01@\x01\x01p\x01\0\x01\x04\0\x0becho-person\x01\
\x04\x01@\x01\x01p\x03\0\x03\x04\0\x0aecho-point\x01\x05\x01@\x03\x04names\x03ag\
ey\x05emails\0\x01\x04\0\x0dcreate-person\x01\x06\x04\0%wasmtime4j:records/with-\
records@0.1.0\x04\0\x0b\x12\x01\0\x0cwith-records\x03\0\0\0G\x09producers\x01\x0c\
processed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
