/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnContextFactory */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnContextFactory
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnContextFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnContextFactory
 * Method:    nativeCreateContext
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnContextFactory_nativeCreateContext
  (JNIEnv *, jclass);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnContextFactory
 * Method:    nativeIsNnAvailable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnContextFactory_nativeIsNnAvailable
  (JNIEnv *, jclass);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnContextFactory
 * Method:    nativeGetDefaultExecutionTarget
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnContextFactory_nativeGetDefaultExecutionTarget
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
