/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniCodeBuilder */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniCodeBuilder
#define _Included_ai_tegmentum_wasmtime4j_jni_JniCodeBuilder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniCodeBuilder
 * Method:    nativeCreate
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniCodeBuilder_nativeCreate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniCodeBuilder
 * Method:    nativeWasmBinary
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniCodeBuilder_nativeWasmBinary
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniCodeBuilder
 * Method:    nativeWasmBinaryOrText
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniCodeBuilder_nativeWasmBinaryOrText
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniCodeBuilder
 * Method:    nativeDwarfPackage
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniCodeBuilder_nativeDwarfPackage
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniCodeBuilder
 * Method:    nativeHint
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniCodeBuilder_nativeHint
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniCodeBuilder
 * Method:    nativeCompileTimeBuiltinsBinary
 * Signature: (JLjava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniCodeBuilder_nativeCompileTimeBuiltinsBinary
  (JNIEnv *, jclass, jlong, jstring, jbyteArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniCodeBuilder
 * Method:    nativeCompileTimeBuiltinsBinaryOrText
 * Signature: (JLjava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniCodeBuilder_nativeCompileTimeBuiltinsBinaryOrText
  (JNIEnv *, jclass, jlong, jstring, jbyteArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniCodeBuilder
 * Method:    nativeExposeUnsafeIntrinsics
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniCodeBuilder_nativeExposeUnsafeIntrinsics
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniCodeBuilder
 * Method:    nativeCompileModule
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniCodeBuilder_nativeCompileModule
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniCodeBuilder
 * Method:    nativeCompileModuleSerialized
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniCodeBuilder_nativeCompileModuleSerialized
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniCodeBuilder
 * Method:    nativeCompileComponent
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniCodeBuilder_nativeCompileComponent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniCodeBuilder
 * Method:    nativeCompileComponentSerialized
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniCodeBuilder_nativeCompileComponentSerialized
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniCodeBuilder
 * Method:    nativeDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniCodeBuilder_nativeDestroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
