/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_cli_JniWasiExit */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_cli_JniWasiExit
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_cli_JniWasiExit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_cli_JniWasiExit
 * Method:    nativeExit
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_cli_JniWasiExit_nativeExit
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
