/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor
 * Method:    nativeReadViaStream
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor_nativeReadViaStream
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor
 * Method:    nativeWriteViaStream
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor_nativeWriteViaStream
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor
 * Method:    nativeAppendViaStream
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor_nativeAppendViaStream
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor
 * Method:    nativeGetType
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor_nativeGetType
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor
 * Method:    nativeGetFlags
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor_nativeGetFlags
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor
 * Method:    nativeSetSize
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor_nativeSetSize
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor
 * Method:    nativeSyncData
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor_nativeSyncData
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor
 * Method:    nativeSync
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor_nativeSync
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor
 * Method:    nativeOpenAt
 * Signature: (JJLjava/lang/String;III)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor_nativeOpenAt
  (JNIEnv *, jclass, jlong, jlong, jstring, jint, jint, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor
 * Method:    nativeCreateDirectoryAt
 * Signature: (JJLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor_nativeCreateDirectoryAt
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor
 * Method:    nativeReadDirectory
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor_nativeReadDirectory
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor
 * Method:    nativeReadLinkAt
 * Signature: (JJLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor_nativeReadLinkAt
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor
 * Method:    nativeUnlinkFileAt
 * Signature: (JJLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor_nativeUnlinkFileAt
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor
 * Method:    nativeRemoveDirectoryAt
 * Signature: (JJLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor_nativeRemoveDirectoryAt
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor
 * Method:    nativeRenameAt
 * Signature: (JJLjava/lang/String;JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor_nativeRenameAt
  (JNIEnv *, jclass, jlong, jlong, jstring, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor
 * Method:    nativeSymlinkAt
 * Signature: (JJLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor_nativeSymlinkAt
  (JNIEnv *, jclass, jlong, jlong, jstring, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor
 * Method:    nativeLinkAt
 * Signature: (JJILjava/lang/String;JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor_nativeLinkAt
  (JNIEnv *, jclass, jlong, jlong, jint, jstring, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor
 * Method:    nativeIsSameObject
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor_nativeIsSameObject
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor
 * Method:    nativeClose
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_filesystem_JniWasiDescriptor_nativeClose
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
