/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiNetwork */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiNetwork
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiNetwork
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiNetwork
 * Method:    nativeCreate
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiNetwork_nativeCreate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiNetwork
 * Method:    nativeClose
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiNetwork_nativeClose
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
