/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniFunctionReference */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniFunctionReference
#define _Included_ai_tegmentum_wasmtime4j_jni_JniFunctionReference
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniFunctionReference
 * Method:    nativeCreateFunctionReferenceFromHost
 * Signature: (J[BJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniFunctionReference_nativeCreateFunctionReferenceFromHost
  (JNIEnv *, jclass, jlong, jbyteArray, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniFunctionReference
 * Method:    nativeCreateFunctionReferenceFromWasm
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniFunctionReference_nativeCreateFunctionReferenceFromWasm
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniFunctionReference
 * Method:    nativeGetRegistryId
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniFunctionReference_nativeGetRegistryId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniFunctionReference
 * Method:    nativeCallFunctionReference
 * Signature: (JJ[B[B)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniFunctionReference_nativeCallFunctionReference
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
