/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniTable */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniTable
#define _Included_ai_tegmentum_wasmtime4j_jni_JniTable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTable
 * Method:    nativeGetSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTable_nativeGetSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTable
 * Method:    nativeGetElementType
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTable_nativeGetElementType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTable
 * Method:    nativeGet
 * Signature: (JI)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTable_nativeGet
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTable
 * Method:    nativeSet
 * Signature: (JILjava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTable_nativeSet
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTable
 * Method:    nativeGrow
 * Signature: (JILjava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTable_nativeGrow
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTable
 * Method:    nativeFill
 * Signature: (JIILjava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTable_nativeFill
  (JNIEnv *, jclass, jlong, jint, jint, jobject);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTable
 * Method:    nativeDestroyTable
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTable_nativeDestroyTable
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
