/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniModule */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniModule
#define _Included_ai_tegmentum_wasmtime4j_jni_JniModule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniModule
 * Method:    nativeInstantiateModule
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniModule_nativeInstantiateModule
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniModule
 * Method:    nativeGetExportedFunctions
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniModule_nativeGetExportedFunctions
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniModule
 * Method:    nativeGetExportedMemories
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniModule_nativeGetExportedMemories
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniModule
 * Method:    nativeGetExportedTables
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniModule_nativeGetExportedTables
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniModule
 * Method:    nativeGetExportedGlobals
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniModule_nativeGetExportedGlobals
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniModule
 * Method:    nativeGetImportedFunctions
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniModule_nativeGetImportedFunctions
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniModule
 * Method:    nativeValidateModule
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniModule_nativeValidateModule
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniModule
 * Method:    nativeGetModuleSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniModule_nativeGetModuleSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniModule
 * Method:    nativeDestroyModule
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniModule_nativeDestroyModule
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
