/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnContext */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnContext
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnContext
 * Method:    nativeCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnContext_nativeCreate
  (JNIEnv *, jclass);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnContext
 * Method:    nativeIsAvailable
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnContext_nativeIsAvailable
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnContext
 * Method:    nativeSupportedEncodings
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnContext_nativeSupportedEncodings
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnContext
 * Method:    nativeLoadGraph
 * Signature: (J[[BII)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnContext_nativeLoadGraph
  (JNIEnv *, jclass, jlong, jobjectArray, jint, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnContext
 * Method:    nativeGetBackendInfo
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnContext_nativeGetBackendInfo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnContext
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnContext_nativeClose
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
