/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalIO */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalIO
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalIO
#ifdef __cplusplus
extern "C" {
#endif
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalIO_MAX_CONCURRENT_IO_OPERATIONS
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalIO_MAX_CONCURRENT_IO_OPERATIONS 1000L
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalIO_MAX_MMAP_SIZE
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalIO_MAX_MMAP_SIZE 2147483648LL
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalIO_MAX_VECTOR_BUFFERS
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalIO_MAX_VECTOR_BUFFERS 1024L
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalIO
 * Method:    nativeAsyncReadFile
 * Signature: (JJJJLjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalIO_nativeAsyncReadFile
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jobject, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalIO
 * Method:    nativeAsyncWriteFile
 * Signature: (JJJJLjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalIO_nativeAsyncWriteFile
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jobject, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalIO
 * Method:    nativeCreateMemoryMapping
 * Signature: (JJJJJII)Lai/tegmentum/wasmtime4j/jni/wasi/WasiExperimentalIO/MemoryMappingResult;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalIO_nativeCreateMemoryMapping
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jint, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalIO
 * Method:    nativeAcquireFileLock
 * Signature: (JJJJJIZ)Lai/tegmentum/wasmtime4j/jni/wasi/WasiExperimentalIO/FileLockResult;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalIO_nativeAcquireFileLock
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jint, jboolean);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalIO
 * Method:    nativeCreateDirectoryWatcher
 * Signature: (JJLjava/lang/String;ZI)Lai/tegmentum/wasmtime4j/jni/wasi/WasiExperimentalIO/DirectoryWatcherResult;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalIO_nativeCreateDirectoryWatcher
  (JNIEnv *, jclass, jlong, jlong, jstring, jboolean, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalIO
 * Method:    nativeVectoredRead
 * Signature: (JJJ[Ljava/nio/ByteBuffer;[I)Lai/tegmentum/wasmtime4j/jni/wasi/WasiExperimentalIO/VectoredIOResult;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalIO_nativeVectoredRead
  (JNIEnv *, jclass, jlong, jlong, jlong, jobjectArray, jintArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalIO
 * Method:    nativeVectoredWrite
 * Signature: (JJJ[Ljava/nio/ByteBuffer;[I)Lai/tegmentum/wasmtime4j/jni/wasi/WasiExperimentalIO/VectoredIOResult;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalIO_nativeVectoredWrite
  (JNIEnv *, jclass, jlong, jlong, jlong, jobjectArray, jintArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalIO
 * Method:    nativeReleaseFileLock
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalIO_nativeReleaseFileLock
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalIO
 * Method:    nativeUnmapMemoryMapping
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalIO_nativeUnmapMemoryMapping
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalIO
 * Method:    nativeStopDirectoryWatcher
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalIO_nativeStopDirectoryWatcher
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalIO
 * Method:    nativeCancelAsyncOperation
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalIO_nativeCancelAsyncOperation
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
