/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniComponentInstancePre */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniComponentInstancePre
#define _Included_ai_tegmentum_wasmtime4j_jni_JniComponentInstancePre
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponentInstancePre
 * Method:    nativeInstantiate
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponentInstancePre_nativeInstantiate
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponentInstancePre
 * Method:    nativeInstantiateWithConfig
 * Signature: (JJJJJJJJJZ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponentInstancePre_nativeInstantiateWithConfig
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jboolean);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponentInstancePre
 * Method:    nativeIsValid
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponentInstancePre_nativeIsValid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponentInstancePre
 * Method:    nativeInstanceCount
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponentInstancePre_nativeInstanceCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponentInstancePre
 * Method:    nativePreparationTimeNs
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponentInstancePre_nativePreparationTimeNs
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponentInstancePre
 * Method:    nativeAvgInstantiationTimeNs
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponentInstancePre_nativeAvgInstantiationTimeNs
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponentInstancePre
 * Method:    nativeDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponentInstancePre_nativeDestroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
