/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniHostFunction */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniHostFunction
#define _Included_ai_tegmentum_wasmtime4j_jni_JniHostFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniHostFunction
 * Method:    nativeCreateHostFunction
 * Signature: (JLjava/lang/String;[BJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniHostFunction_nativeCreateHostFunction
  (JNIEnv *, jclass, jlong, jstring, jbyteArray, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniHostFunction
 * Method:    nativeDestroyHostFunction
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniHostFunction_nativeDestroyHostFunction
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
