/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl
#define _Included_ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl
 * Method:    nativeSetArgv
 * Signature: (J[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl_nativeSetArgv
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl
 * Method:    nativeSetEnv
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl_nativeSetEnv
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl
 * Method:    nativeInheritEnv
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl_nativeInheritEnv
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl
 * Method:    nativeInheritStdio
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl_nativeInheritStdio
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl
 * Method:    nativeSetStdin
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl_nativeSetStdin
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl
 * Method:    nativeSetStdout
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl_nativeSetStdout
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl
 * Method:    nativeSetStderr
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl_nativeSetStderr
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl
 * Method:    nativePreopenedDir
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl_nativePreopenedDir
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl
 * Method:    nativePreopenedDirReadOnly
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl_nativePreopenedDirReadOnly
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl
 * Method:    nativeSetWorkingDirectory
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl_nativeSetWorkingDirectory
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl
 * Method:    nativeSetNetworkEnabled
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl_nativeSetNetworkEnabled
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl
 * Method:    nativeSetMaxOpenFiles
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl_nativeSetMaxOpenFiles
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl
 * Method:    nativeSetAsyncIoEnabled
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl_nativeSetAsyncIoEnabled
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl
 * Method:    nativeSetMaxAsyncOperations
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl_nativeSetMaxAsyncOperations
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl
 * Method:    nativeSetAsyncTimeout
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl_nativeSetAsyncTimeout
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl
 * Method:    nativeSetComponentModelEnabled
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl_nativeSetComponentModelEnabled
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl
 * Method:    nativeSetProcessEnabled
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl_nativeSetProcessEnabled
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl
 * Method:    nativeSetFilesystemWorkingDir
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl_nativeSetFilesystemWorkingDir
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl
 * Method:    nativePreopenedDirWithPermissions
 * Signature: (JLjava/lang/String;Ljava/lang/String;ZZZZZZZ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl_nativePreopenedDirWithPermissions
  (JNIEnv *, jclass, jlong, jstring, jstring, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl
 * Method:    nativeCleanup
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasiContextImpl_nativeCleanup
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
