/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_clocks_JniWasiMonotonicClock */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_clocks_JniWasiMonotonicClock
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_clocks_JniWasiMonotonicClock
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_clocks_JniWasiMonotonicClock
 * Method:    nativeNow
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_clocks_JniWasiMonotonicClock_nativeNow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_clocks_JniWasiMonotonicClock
 * Method:    nativeResolution
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_clocks_JniWasiMonotonicClock_nativeResolution
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_clocks_JniWasiMonotonicClock
 * Method:    nativeSubscribeInstant
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_clocks_JniWasiMonotonicClock_nativeSubscribeInstant
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_clocks_JniWasiMonotonicClock
 * Method:    nativeSubscribeDuration
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_clocks_JniWasiMonotonicClock_nativeSubscribeDuration
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
