/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_WasiEnvironmentOperationsPreview2 */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_WasiEnvironmentOperationsPreview2
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_WasiEnvironmentOperationsPreview2
#ifdef __cplusplus
extern "C" {
#endif
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiEnvironmentOperationsPreview2_MAX_ENVIRONMENT_VARIABLES
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiEnvironmentOperationsPreview2_MAX_ENVIRONMENT_VARIABLES 1000L
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiEnvironmentOperationsPreview2_MAX_ENV_LENGTH
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiEnvironmentOperationsPreview2_MAX_ENV_LENGTH 32768L
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiEnvironmentOperationsPreview2_MAX_ARGUMENTS
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiEnvironmentOperationsPreview2_MAX_ARGUMENTS 1000L
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiEnvironmentOperationsPreview2_MAX_ARG_LENGTH
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiEnvironmentOperationsPreview2_MAX_ARG_LENGTH 32768L
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiEnvironmentOperationsPreview2
 * Method:    nativeGetEnvironment
 * Signature: (J)Lai/tegmentum/wasmtime4j/jni/wasi/WasiEnvironmentOperationsPreview2/EnvironmentResult;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiEnvironmentOperationsPreview2_nativeGetEnvironment
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiEnvironmentOperationsPreview2
 * Method:    nativeGetArguments
 * Signature: (J)Lai/tegmentum/wasmtime4j/jni/wasi/WasiEnvironmentOperationsPreview2/ArgumentsResult;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiEnvironmentOperationsPreview2_nativeGetArguments
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiEnvironmentOperationsPreview2
 * Method:    nativeExit
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiEnvironmentOperationsPreview2_nativeExit
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
