/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_type_JniGlobalType */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_type_JniGlobalType
#define _Included_ai_tegmentum_wasmtime4j_jni_type_JniGlobalType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_type_JniGlobalType
 * Method:    nativeGetGlobalTypeInfo
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_type_JniGlobalType_nativeGetGlobalTypeInfo
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
