/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworking */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworking
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworking
#ifdef __cplusplus
extern "C" {
#endif
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworking_MAX_POOL_CONNECTIONS
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworking_MAX_POOL_CONNECTIONS 100L
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworking_MAX_WEBSOCKET_FRAME_SIZE
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworking_MAX_WEBSOCKET_FRAME_SIZE 1048576L
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworking
 * Method:    nativeCreateHttp2Connection
 * Signature: (JJLjava/lang/String;IZIIZIJ)Lai/tegmentum/wasmtime4j/jni/wasi/WasiAdvancedNetworking/Http2ConnectionResult;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworking_nativeCreateHttp2Connection
  (JNIEnv *, jclass, jlong, jlong, jstring, jint, jboolean, jint, jint, jboolean, jint, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworking
 * Method:    nativeCreateHttp3Connection
 * Signature: (JJLjava/lang/String;IIIJJLjava/lang/String;)Lai/tegmentum/wasmtime4j/jni/wasi/WasiAdvancedNetworking/Http3ConnectionResult;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworking_nativeCreateHttp3Connection
  (JNIEnv *, jclass, jlong, jlong, jstring, jint, jint, jint, jlong, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworking
 * Method:    nativeHttp2Request
 * Signature: (JJLjava/lang/String;Ljava/lang/String;[Ljava/lang/String;[BI)Lai/tegmentum/wasmtime4j/jni/wasi/WasiAdvancedNetworking/Http2ResponseResult;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworking_nativeHttp2Request
  (JNIEnv *, jclass, jlong, jlong, jstring, jstring, jobjectArray, jbyteArray, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworking
 * Method:    nativeCreateWebSocket
 * Signature: (JJLjava/lang/String;[Ljava/lang/String;[Ljava/lang/String;IJZ)Lai/tegmentum/wasmtime4j/jni/wasi/WasiAdvancedNetworking/WebSocketConnectionResult;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworking_nativeCreateWebSocket
  (JNIEnv *, jclass, jlong, jlong, jstring, jobjectArray, jobjectArray, jint, jlong, jboolean);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworking
 * Method:    nativeSendWebSocketMessage
 * Signature: (JJ[BII)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworking_nativeSendWebSocketMessage
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworking
 * Method:    nativeReceiveWebSocketMessage
 * Signature: (JJ[BJ)Lai/tegmentum/wasmtime4j/jni/wasi/WasiAdvancedNetworking/WebSocketReceiveResult;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworking_nativeReceiveWebSocketMessage
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworking
 * Method:    nativeEnableUdpMulticast
 * Signature: (JJLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworking_nativeEnableUdpMulticast
  (JNIEnv *, jclass, jlong, jlong, jstring, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworking
 * Method:    nativeListNetworkInterfaces
 * Signature: (J)[Lai/tegmentum/wasmtime4j/jni/wasi/WasiAdvancedNetworking/NetworkInterfaceInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworking_nativeListNetworkInterfaces
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworking
 * Method:    nativeCloseConnection
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworking_nativeCloseConnection
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
