/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiIpNameLookup */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiIpNameLookup
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiIpNameLookup
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiIpNameLookup
 * Method:    nativeResolveAddresses
 * Signature: (JJLjava/lang/String;B)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiIpNameLookup_nativeResolveAddresses
  (JNIEnv *, jclass, jlong, jlong, jstring, jbyte);

#ifdef __cplusplus
}
#endif
#endif
