/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_nativelib_NativeMethodBindings */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_nativelib_NativeMethodBindings
#define _Included_ai_tegmentum_wasmtime4j_jni_nativelib_NativeMethodBindings
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_nativelib_NativeMethodBindings
 * Method:    nativeGetWasmtimeVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_tegmentum_wasmtime4j_jni_nativelib_NativeMethodBindings_nativeGetWasmtimeVersion
  (JNIEnv *, jclass);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_nativelib_NativeMethodBindings
 * Method:    nativeCreateRuntime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_nativelib_NativeMethodBindings_nativeCreateRuntime
  (JNIEnv *, jclass);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_nativelib_NativeMethodBindings
 * Method:    nativeDestroyRuntime
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_nativelib_NativeMethodBindings_nativeDestroyRuntime
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_nativelib_NativeMethodBindings
 * Method:    nativeInitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_nativelib_NativeMethodBindings_nativeInitialize
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
