/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniTable */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniTable
#define _Included_ai_tegmentum_wasmtime4j_jni_JniTable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTable
 * Method:    nativeGetSize
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTable_nativeGetSize
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTable
 * Method:    nativeGetMaxSize
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTable_nativeGetMaxSize
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTable
 * Method:    nativeGetElementType
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTable_nativeGetElementType
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTable
 * Method:    nativeGet
 * Signature: (JJI)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTable_nativeGet
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTable
 * Method:    nativeSet
 * Signature: (JJILjava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTable_nativeSet
  (JNIEnv *, jclass, jlong, jlong, jint, jobject);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTable
 * Method:    nativeGrow
 * Signature: (JILjava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTable_nativeGrow
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTable
 * Method:    nativeTableGrow
 * Signature: (JJIJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTable_nativeTableGrow
  (JNIEnv *, jclass, jlong, jlong, jint, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTable
 * Method:    nativeFill
 * Signature: (JIILjava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTable_nativeFill
  (JNIEnv *, jclass, jlong, jint, jint, jobject);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTable
 * Method:    nativeTableFill
 * Signature: (JJIJI)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTable_nativeTableFill
  (JNIEnv *, jclass, jlong, jlong, jint, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTable
 * Method:    nativeCopy
 * Signature: (JIII)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTable_nativeCopy
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTable
 * Method:    nativeCopyFromTable
 * Signature: (JIJII)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTable_nativeCopyFromTable
  (JNIEnv *, jclass, jlong, jint, jlong, jint, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTable
 * Method:    nativeDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTable_nativeDestroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTable
 * Method:    nativeGetTableTypeInfo
 * Signature: (JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTable_nativeGetTableTypeInfo
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTable
 * Method:    nativeSupports64BitAddressing
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTable_nativeSupports64BitAddressing
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
