/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniSerializer */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniSerializer
#define _Included_ai_tegmentum_wasmtime4j_jni_JniSerializer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniSerializer
 * Method:    nativeSerialize
 * Signature: (JJ[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniSerializer_nativeSerialize
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniSerializer
 * Method:    nativeDeserialize
 * Signature: (JJ[B)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniSerializer_nativeDeserialize
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniSerializer
 * Method:    nativeClearCache
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniSerializer_nativeClearCache
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniSerializer
 * Method:    nativeGetCacheEntryCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniSerializer_nativeGetCacheEntryCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniSerializer
 * Method:    nativeGetCacheTotalSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniSerializer_nativeGetCacheTotalSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniSerializer
 * Method:    nativeGetCacheHitRate
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniSerializer_nativeGetCacheHitRate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniSerializer
 * Method:    nativeDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniSerializer_nativeDestroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
