/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniWastRunner */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniWastRunner
#define _Included_ai_tegmentum_wasmtime4j_jni_JniWastRunner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWastRunner
 * Method:    nativeExecuteWastFile
 * Signature: (Ljava/lang/String;)Lai/tegmentum/wasmtime4j/wast/WastExecutionResult;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWastRunner_nativeExecuteWastFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWastRunner
 * Method:    nativeExecuteWastBuffer
 * Signature: (Ljava/lang/String;[B)Lai/tegmentum/wasmtime4j/wast/WastExecutionResult;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWastRunner_nativeExecuteWastBuffer
  (JNIEnv *, jclass, jstring, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
