/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_type_JniExportDescriptor */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_type_JniExportDescriptor
#define _Included_ai_tegmentum_wasmtime4j_jni_type_JniExportDescriptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_type_JniExportDescriptor
 * Method:    nativeGetExportName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_tegmentum_wasmtime4j_jni_type_JniExportDescriptor_nativeGetExportName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_type_JniExportDescriptor
 * Method:    nativeGetExportTypeInfo
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_type_JniExportDescriptor_nativeGetExportTypeInfo
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
