/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniWeakEngine */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniWeakEngine
#define _Included_ai_tegmentum_wasmtime4j_jni_JniWeakEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWeakEngine
 * Method:    nativeUpgrade
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWeakEngine_nativeUpgrade
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWeakEngine
 * Method:    nativeDestroyWeakEngine
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWeakEngine_nativeDestroyWeakEngine
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
