/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiInputStream */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiInputStream
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiInputStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiInputStream
 * Method:    nativeRead
 * Signature: (JJJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiInputStream_nativeRead
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiInputStream
 * Method:    nativeBlockingRead
 * Signature: (JJJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiInputStream_nativeBlockingRead
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiInputStream
 * Method:    nativeSkip
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiInputStream_nativeSkip
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiInputStream
 * Method:    nativeSubscribe
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiInputStream_nativeSubscribe
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiInputStream
 * Method:    nativeClose
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiInputStream_nativeClose
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
