/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniInstance */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniInstance
#define _Included_ai_tegmentum_wasmtime4j_jni_JniInstance
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniInstance
 * Method:    nativeGetFunction
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniInstance_nativeGetFunction
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniInstance
 * Method:    nativeGetMemory
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniInstance_nativeGetMemory
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniInstance
 * Method:    nativeGetTable
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniInstance_nativeGetTable
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniInstance
 * Method:    nativeGetGlobal
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniInstance_nativeGetGlobal
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniInstance
 * Method:    nativeHasExport
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniInstance_nativeHasExport
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniInstance
 * Method:    nativeGetExportNames
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniInstance_nativeGetExportNames
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniInstance
 * Method:    nativeDestroyInstance
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniInstance_nativeDestroyInstance
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniInstance
 * Method:    nativeDispose
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniInstance_nativeDispose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniInstance
 * Method:    nativeIsDisposed
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniInstance_nativeIsDisposed
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniInstance
 * Method:    nativeGetCreatedAtMicros
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniInstance_nativeGetCreatedAtMicros
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniInstance
 * Method:    nativeGetMetadataExportCount
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniInstance_nativeGetMetadataExportCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniInstance
 * Method:    nativeCallI32Function
 * Signature: (JLjava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniInstance_nativeCallI32Function
  (JNIEnv *, jclass, jlong, jstring, jintArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniInstance
 * Method:    nativeCallI32FunctionNoParams
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniInstance_nativeCallI32FunctionNoParams
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniInstance
 * Method:    nativeGetState
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniInstance_nativeGetState
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniInstance
 * Method:    nativeCleanupResources
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniInstance_nativeCleanupResources
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniInstance
 * Method:    nativeValidateThreadAccess
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniInstance_nativeValidateThreadAccess
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
