/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_cli_JniWasiEnvironment */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_cli_JniWasiEnvironment
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_cli_JniWasiEnvironment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_cli_JniWasiEnvironment
 * Method:    nativeGetAll
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_cli_JniWasiEnvironment_nativeGetAll
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_cli_JniWasiEnvironment
 * Method:    nativeGet
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_cli_JniWasiEnvironment_nativeGet
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_cli_JniWasiEnvironment
 * Method:    nativeGetArguments
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_cli_JniWasiEnvironment_nativeGetArguments
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_cli_JniWasiEnvironment
 * Method:    nativeGetInitialCwd
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_cli_JniWasiEnvironment_nativeGetInitialCwd
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
