/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_execution_JniResourceLimiter */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_execution_JniResourceLimiter
#define _Included_ai_tegmentum_wasmtime4j_jni_execution_JniResourceLimiter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_execution_JniResourceLimiter
 * Method:    nativeCreate
 * Signature: (JJJIII)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_execution_JniResourceLimiter_nativeCreate
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jint, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_execution_JniResourceLimiter
 * Method:    nativeCreateDefault
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_execution_JniResourceLimiter_nativeCreateDefault
  (JNIEnv *, jclass);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_execution_JniResourceLimiter
 * Method:    nativeFree
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_execution_JniResourceLimiter_nativeFree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_execution_JniResourceLimiter
 * Method:    nativeAllowMemoryGrow
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_execution_JniResourceLimiter_nativeAllowMemoryGrow
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_execution_JniResourceLimiter
 * Method:    nativeAllowTableGrow
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_execution_JniResourceLimiter_nativeAllowTableGrow
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_execution_JniResourceLimiter
 * Method:    nativeGetStatsJson
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_tegmentum_wasmtime4j_jni_execution_JniResourceLimiter_nativeGetStatsJson
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_execution_JniResourceLimiter
 * Method:    nativeResetStats
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_execution_JniResourceLimiter_nativeResetStats
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_execution_JniResourceLimiter
 * Method:    nativeGetCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_execution_JniResourceLimiter_nativeGetCount
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
