/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_WasiRandomOperationsPreview2 */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_WasiRandomOperationsPreview2
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_WasiRandomOperationsPreview2
#ifdef __cplusplus
extern "C" {
#endif
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiRandomOperationsPreview2_MAX_RANDOM_BYTES
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiRandomOperationsPreview2_MAX_RANDOM_BYTES 1048576L
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiRandomOperationsPreview2
 * Method:    nativeGetRandomBytes
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiRandomOperationsPreview2_nativeGetRandomBytes
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiRandomOperationsPreview2
 * Method:    nativeGetRandomU32
 * Signature: (J)Lai/tegmentum/wasmtime4j/jni/wasi/WasiRandomOperationsPreview2/RandomU32Result;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiRandomOperationsPreview2_nativeGetRandomU32
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiRandomOperationsPreview2
 * Method:    nativeGetRandomU64
 * Signature: (J)Lai/tegmentum/wasmtime4j/jni/wasi/WasiRandomOperationsPreview2/RandomU64Result;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiRandomOperationsPreview2_nativeGetRandomU64
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiRandomOperationsPreview2
 * Method:    nativeSeedRandom
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiRandomOperationsPreview2_nativeSeedRandom
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
