/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniStore */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniStore
#define _Included_ai_tegmentum_wasmtime4j_jni_JniStore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeCreateStoreForModule
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeCreateStoreForModule
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeAddFuel
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeAddFuel
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeSetFuel
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeSetFuel
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeGetFuelRemaining
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeGetFuelRemaining
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeSetEpochDeadline
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeSetEpochDeadline
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeValidate
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeValidate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeConsumeFuel
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeConsumeFuel
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeCreateGlobal
 * Signature: (JII[Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeCreateGlobal
  (JNIEnv *, jclass, jlong, jint, jint, jobjectArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeCreateTable
 * Signature: (JIII)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeCreateTable
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeCreateMemory
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeCreateMemory
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeCreateSharedMemory
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeCreateSharedMemory
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeCreateMemoryWithType
 * Signature: (JJJII)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeCreateMemoryWithType
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeCreateTable64
 * Signature: (JIJIJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeCreateTable64
  (JNIEnv *, jclass, jlong, jint, jlong, jint, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeCreateInstanceWithImports
 * Signature: (JJ[J[I)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeCreateInstanceWithImports
  (JNIEnv *, jclass, jlong, jlong, jlongArray, jintArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeDestroyStore
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeDestroyStore
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeGc
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeGc
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeThrowException
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeThrowException
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeTakePendingException
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeTakePendingException
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeHasPendingException
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeHasPendingException
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeEpochDeadlineAsyncYieldAndUpdate
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeEpochDeadlineAsyncYieldAndUpdate
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeEpochDeadlineTrap
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeEpochDeadlineTrap
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeSetEpochDeadlineCallback
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeSetEpochDeadlineCallback
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeClearEpochDeadlineCallback
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeClearEpochDeadlineCallback
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeSetCallHook
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeSetCallHook
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeClearCallHook
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeClearCallHook
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeSetCallHookAsync
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeSetCallHookAsync
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeClearCallHookAsync
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeClearCallHookAsync
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeSetResourceLimiter
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeSetResourceLimiter
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeClearResourceLimiter
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeClearResourceLimiter
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeSetResourceLimiterAsync
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeSetResourceLimiterAsync
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeSetFuelAsyncYieldInterval
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeSetFuelAsyncYieldInterval
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeIsSingleStep
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeIsSingleStep
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeIsAsync
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeIsAsync
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeBreakpointCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeBreakpointCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeAddBreakpoint
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeAddBreakpoint
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeRemoveBreakpoint
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeRemoveBreakpoint
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniStore
 * Method:    nativeSetSingleStep
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniStore_nativeSetSingleStep
  (JNIEnv *, jclass, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
