/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniComponentLinker */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniComponentLinker
#define _Included_ai_tegmentum_wasmtime4j_jni_JniComponentLinker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponentLinker
 * Method:    nativeEnableWasiP2
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponentLinker_nativeEnableWasiP2
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponentLinker
 * Method:    nativeDestroyComponentLinker
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponentLinker_nativeDestroyComponentLinker
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
