/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_http_JniWasiHttpContext */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_http_JniWasiHttpContext
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_http_JniWasiHttpContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_http_JniWasiHttpContext
 * Method:    nativeCreate
 * Signature: (Lai/tegmentum/wasmtime4j/wasi/http/WasiHttpConfig;)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_http_JniWasiHttpContext_nativeCreate
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_http_JniWasiHttpContext
 * Method:    nativeIsValid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_http_JniWasiHttpContext_nativeIsValid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_http_JniWasiHttpContext
 * Method:    nativeResetStats
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_http_JniWasiHttpContext_nativeResetStats
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_http_JniWasiHttpContext
 * Method:    nativeFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_http_JniWasiHttpContext_nativeFree
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
