/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniMemory */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniMemory
#define _Included_ai_tegmentum_wasmtime4j_jni_JniMemory
#ifdef __cplusplus
extern "C" {
#endif
#undef ai_tegmentum_wasmtime4j_jni_JniMemory_BUFFER_CACHE_VALIDITY_MS
#define ai_tegmentum_wasmtime4j_jni_JniMemory_BUFFER_CACHE_VALIDITY_MS 100LL
#undef ai_tegmentum_wasmtime4j_jni_JniMemory_BULK_OPERATION_THRESHOLD
#define ai_tegmentum_wasmtime4j_jni_JniMemory_BULK_OPERATION_THRESHOLD 1024L
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeGetSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeGetSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeGrow
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeGrow
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeReadByte
 * Signature: (JJJ)B
 */
JNIEXPORT jbyte JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeReadByte
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeWriteByte
 * Signature: (JJJB)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeWriteByte
  (JNIEnv *, jclass, jlong, jlong, jlong, jbyte);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeReadBytes
 * Signature: (JJJ[B)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeReadBytes
  (JNIEnv *, jclass, jlong, jlong, jlong, jbyteArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeWriteBytes
 * Signature: (JJJ[B)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeWriteBytes
  (JNIEnv *, jclass, jlong, jlong, jlong, jbyteArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeGetBuffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeGetBuffer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeGetMemoryTypeInfo
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeGetMemoryTypeInfo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeMemoryCopy
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeMemoryCopy
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeMemoryFill
 * Signature: (JIBI)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeMemoryFill
  (JNIEnv *, jclass, jlong, jint, jbyte, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeMemoryInit
 * Signature: (JJJIIII)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeMemoryInit
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jint, jint, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeDataDrop
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeDataDrop
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeIsShared
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeIsShared
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeAtomicCompareAndSwapInt
 * Signature: (JJIII)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeAtomicCompareAndSwapInt
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeAtomicCompareAndSwapLong
 * Signature: (JJIJJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeAtomicCompareAndSwapLong
  (JNIEnv *, jclass, jlong, jlong, jint, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeAtomicLoadInt
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeAtomicLoadInt
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeAtomicLoadLong
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeAtomicLoadLong
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeAtomicStoreInt
 * Signature: (JJII)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeAtomicStoreInt
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeAtomicStoreLong
 * Signature: (JJIJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeAtomicStoreLong
  (JNIEnv *, jclass, jlong, jlong, jint, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeAtomicAddInt
 * Signature: (JJII)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeAtomicAddInt
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeAtomicAddLong
 * Signature: (JJIJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeAtomicAddLong
  (JNIEnv *, jclass, jlong, jlong, jint, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeAtomicAndInt
 * Signature: (JJII)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeAtomicAndInt
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeAtomicOrInt
 * Signature: (JJII)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeAtomicOrInt
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeAtomicXorInt
 * Signature: (JJII)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeAtomicXorInt
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeAtomicAndLong
 * Signature: (JJIJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeAtomicAndLong
  (JNIEnv *, jclass, jlong, jlong, jint, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeAtomicOrLong
 * Signature: (JJIJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeAtomicOrLong
  (JNIEnv *, jclass, jlong, jlong, jint, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeAtomicXorLong
 * Signature: (JJIJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeAtomicXorLong
  (JNIEnv *, jclass, jlong, jlong, jint, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeAtomicFence
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeAtomicFence
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeAtomicNotify
 * Signature: (JJII)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeAtomicNotify
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeAtomicWait32
 * Signature: (JJIIJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeAtomicWait32
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeAtomicWait64
 * Signature: (JJIJJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeAtomicWait64
  (JNIEnv *, jclass, jlong, jlong, jint, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeGetMaxSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeGetMaxSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeSupports64BitAddressing
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeSupports64BitAddressing
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeMemoryCopy64
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeMemoryCopy64
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeMemoryFill64
 * Signature: (JJBJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeMemoryFill64
  (JNIEnv *, jclass, jlong, jlong, jbyte, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeMemoryInit64
 * Signature: (JJJJIJJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeMemoryInit64
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeGrowAsync
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeGrowAsync
  (JNIEnv *, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
