/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiOutputStream */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiOutputStream
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiOutputStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiOutputStream
 * Method:    nativeCheckWrite
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiOutputStream_nativeCheckWrite
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiOutputStream
 * Method:    nativeWrite
 * Signature: (JJ[B)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiOutputStream_nativeWrite
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiOutputStream
 * Method:    nativeBlockingWriteAndFlush
 * Signature: (JJ[B)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiOutputStream_nativeBlockingWriteAndFlush
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiOutputStream
 * Method:    nativeFlush
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiOutputStream_nativeFlush
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiOutputStream
 * Method:    nativeBlockingFlush
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiOutputStream_nativeBlockingFlush
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiOutputStream
 * Method:    nativeWriteZeroes
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiOutputStream_nativeWriteZeroes
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiOutputStream
 * Method:    nativeBlockingWriteZeroesAndFlush
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiOutputStream_nativeBlockingWriteZeroesAndFlush
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiOutputStream
 * Method:    nativeSplice
 * Signature: (JJJJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiOutputStream_nativeSplice
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiOutputStream
 * Method:    nativeBlockingSplice
 * Signature: (JJJJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiOutputStream_nativeBlockingSplice
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiOutputStream
 * Method:    nativeSubscribe
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiOutputStream_nativeSubscribe
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiOutputStream
 * Method:    nativeClose
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiOutputStream_nativeClose
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
