/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniAsyncRuntime */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniAsyncRuntime
#define _Included_ai_tegmentum_wasmtime4j_jni_JniAsyncRuntime
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniAsyncRuntime
 * Method:    nativeAsyncRuntimeInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniAsyncRuntime_nativeAsyncRuntimeInit
  (JNIEnv *, jclass);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniAsyncRuntime
 * Method:    nativeAsyncRuntimeInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniAsyncRuntime_nativeAsyncRuntimeInfo
  (JNIEnv *, jclass);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniAsyncRuntime
 * Method:    nativeAsyncRuntimeShutdown
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniAsyncRuntime_nativeAsyncRuntimeShutdown
  (JNIEnv *, jclass);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniAsyncRuntime
 * Method:    nativeFuncCallAsync
 * Signature: (JLjava/lang/String;[Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniAsyncRuntime_nativeFuncCallAsync
  (JNIEnv *, jclass, jlong, jstring, jobjectArray, jlong, jobject, jobject);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniAsyncRuntime
 * Method:    nativeModuleCompileAsync
 * Signature: ([BJLjava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniAsyncRuntime_nativeModuleCompileAsync
  (JNIEnv *, jclass, jbyteArray, jlong, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
