/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_threads_JniWasiThreadsContext */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_threads_JniWasiThreadsContext
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_threads_JniWasiThreadsContext
#ifdef __cplusplus
extern "C" {
#endif
#undef ai_tegmentum_wasmtime4j_jni_wasi_threads_JniWasiThreadsContext_MAX_THREAD_ID
#define ai_tegmentum_wasmtime4j_jni_wasi_threads_JniWasiThreadsContext_MAX_THREAD_ID 536870911L
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_threads_JniWasiThreadsContext
 * Method:    nativeSpawn
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_threads_JniWasiThreadsContext_nativeSpawn
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_threads_JniWasiThreadsContext
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_threads_JniWasiThreadsContext_nativeClose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_threads_JniWasiThreadsContext
 * Method:    nativeIsSupported
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_threads_JniWasiThreadsContext_nativeIsSupported
  (JNIEnv *, jclass);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_threads_JniWasiThreadsContext
 * Method:    nativeCreate
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_threads_JniWasiThreadsContext_nativeCreate
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_threads_JniWasiThreadsContext
 * Method:    nativeAddToLinker
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_threads_JniWasiThreadsContext_nativeAddToLinker
  (JNIEnv *, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
