/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniWasmThreadLocalStorage */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniWasmThreadLocalStorage
#define _Included_ai_tegmentum_wasmtime4j_jni_JniWasmThreadLocalStorage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasmThreadLocalStorage
 * Method:    nativePutInt
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasmThreadLocalStorage_nativePutInt
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasmThreadLocalStorage
 * Method:    nativeGetInt
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasmThreadLocalStorage_nativeGetInt
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasmThreadLocalStorage
 * Method:    nativePutLong
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasmThreadLocalStorage_nativePutLong
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasmThreadLocalStorage
 * Method:    nativeGetLong
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasmThreadLocalStorage_nativeGetLong
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasmThreadLocalStorage
 * Method:    nativePutFloat
 * Signature: (JLjava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasmThreadLocalStorage_nativePutFloat
  (JNIEnv *, jclass, jlong, jstring, jfloat);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasmThreadLocalStorage
 * Method:    nativeGetFloat
 * Signature: (JLjava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasmThreadLocalStorage_nativeGetFloat
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasmThreadLocalStorage
 * Method:    nativePutDouble
 * Signature: (JLjava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasmThreadLocalStorage_nativePutDouble
  (JNIEnv *, jclass, jlong, jstring, jdouble);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasmThreadLocalStorage
 * Method:    nativeGetDouble
 * Signature: (JLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasmThreadLocalStorage_nativeGetDouble
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasmThreadLocalStorage
 * Method:    nativePutBytes
 * Signature: (JLjava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasmThreadLocalStorage_nativePutBytes
  (JNIEnv *, jclass, jlong, jstring, jbyteArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasmThreadLocalStorage
 * Method:    nativeGetBytes
 * Signature: (JLjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasmThreadLocalStorage_nativeGetBytes
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasmThreadLocalStorage
 * Method:    nativeRemove
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasmThreadLocalStorage_nativeRemove
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasmThreadLocalStorage
 * Method:    nativeContains
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasmThreadLocalStorage_nativeContains
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasmThreadLocalStorage
 * Method:    nativeClear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasmThreadLocalStorage_nativeClear
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasmThreadLocalStorage
 * Method:    nativeSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasmThreadLocalStorage_nativeSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasmThreadLocalStorage
 * Method:    nativeGetMemoryUsage
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasmThreadLocalStorage_nativeGetMemoryUsage
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
