/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_WasiNetworkOperations */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_WasiNetworkOperations
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_WasiNetworkOperations
#ifdef __cplusplus
extern "C" {
#endif
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiNetworkOperations_AF_INET
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiNetworkOperations_AF_INET 2L
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiNetworkOperations_AF_INET6
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiNetworkOperations_AF_INET6 10L
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiNetworkOperations_MAX_UDP_DATAGRAM_SIZE
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiNetworkOperations_MAX_UDP_DATAGRAM_SIZE 65507L
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiNetworkOperations
 * Method:    nativeCreateTcpSocket
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiNetworkOperations_nativeCreateTcpSocket
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiNetworkOperations
 * Method:    nativeBindTcp
 * Signature: (JJLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiNetworkOperations_nativeBindTcp
  (JNIEnv *, jclass, jlong, jlong, jstring, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiNetworkOperations
 * Method:    nativeListenTcp
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiNetworkOperations_nativeListenTcp
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiNetworkOperations
 * Method:    nativeAcceptTcp
 * Signature: (JJ)Lai/tegmentum/wasmtime4j/jni/wasi/WasiNetworkOperations/TcpAcceptResult;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiNetworkOperations_nativeAcceptTcp
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiNetworkOperations
 * Method:    nativeConnectTcp
 * Signature: (JJLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiNetworkOperations_nativeConnectTcp
  (JNIEnv *, jclass, jlong, jlong, jstring, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiNetworkOperations
 * Method:    nativeSendTcp
 * Signature: (JJ[BI)Lai/tegmentum/wasmtime4j/jni/wasi/WasiNetworkOperations/TcpSendResult;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiNetworkOperations_nativeSendTcp
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiNetworkOperations
 * Method:    nativeReceiveTcp
 * Signature: (JJ[BI)Lai/tegmentum/wasmtime4j/jni/wasi/WasiNetworkOperations/TcpReceiveResult;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiNetworkOperations_nativeReceiveTcp
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiNetworkOperations
 * Method:    nativeCreateUdpSocket
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiNetworkOperations_nativeCreateUdpSocket
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiNetworkOperations
 * Method:    nativeSendUdp
 * Signature: (JJ[BILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiNetworkOperations_nativeSendUdp
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jstring, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiNetworkOperations
 * Method:    nativeReceiveUdp
 * Signature: (JJ[BI)Lai/tegmentum/wasmtime4j/jni/wasi/WasiNetworkOperations/UdpReceiveResult;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiNetworkOperations_nativeReceiveUdp
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiNetworkOperations
 * Method:    nativeHttpRequest
 * Signature: (JLjava/lang/String;Ljava/lang/String;[Ljava/lang/String;[BI)Lai/tegmentum/wasmtime4j/jni/wasi/WasiNetworkOperations/HttpResponse;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiNetworkOperations_nativeHttpRequest
  (JNIEnv *, jclass, jlong, jstring, jstring, jobjectArray, jbyteArray, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiNetworkOperations
 * Method:    nativeCloseSocket
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiNetworkOperations_nativeCloseSocket
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
