/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniFunction */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniFunction
#define _Included_ai_tegmentum_wasmtime4j_jni_JniFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniFunction
 * Method:    nativeGetParameterTypes
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniFunction_nativeGetParameterTypes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniFunction
 * Method:    nativeGetReturnTypes
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniFunction_nativeGetReturnTypes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniFunction
 * Method:    nativeCall
 * Signature: (JJ[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniFunction_nativeCall
  (JNIEnv *, jclass, jlong, jlong, jobjectArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniFunction
 * Method:    nativeCallMultiValue
 * Signature: (JJ[Ljava/lang/Object;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniFunction_nativeCallMultiValue
  (JNIEnv *, jclass, jlong, jlong, jobjectArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniFunction
 * Method:    nativeFuncToRaw
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniFunction_nativeFuncToRaw
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniFunction
 * Method:    nativeFuncFromRaw
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniFunction_nativeFuncFromRaw
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
