/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperations */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperations
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperations
#ifdef __cplusplus
extern "C" {
#endif
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperations_WASI_CLOCK_REALTIME
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperations_WASI_CLOCK_REALTIME 0L
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperations_WASI_CLOCK_MONOTONIC
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperations_WASI_CLOCK_MONOTONIC 1L
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperations_WASI_CLOCK_PROCESS_CPUTIME_ID
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperations_WASI_CLOCK_PROCESS_CPUTIME_ID 2L
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperations_WASI_CLOCK_THREAD_CPUTIME_ID
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperations_WASI_CLOCK_THREAD_CPUTIME_ID 3L
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperations_MAX_CLOCK_ID
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperations_MAX_CLOCK_ID 3L
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperations
 * Method:    nativeGetClockResolution
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperations_nativeGetClockResolution
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperations
 * Method:    nativeGetCurrentTime
 * Signature: (JIJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperations_nativeGetCurrentTime
  (JNIEnv *, jclass, jlong, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
