/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnGraphExecutionContext */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnGraphExecutionContext
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnGraphExecutionContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnGraphExecutionContext
 * Method:    nativeSetInputByIndex
 * Signature: (JI[II[B)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnGraphExecutionContext_nativeSetInputByIndex
  (JNIEnv *, jclass, jlong, jint, jintArray, jint, jbyteArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnGraphExecutionContext
 * Method:    nativeSetInputByName
 * Signature: (JLjava/lang/String;[II[B)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnGraphExecutionContext_nativeSetInputByName
  (JNIEnv *, jclass, jlong, jstring, jintArray, jint, jbyteArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnGraphExecutionContext
 * Method:    nativeCompute
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnGraphExecutionContext_nativeCompute
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnGraphExecutionContext
 * Method:    nativeGetOutputByIndex
 * Signature: (JI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnGraphExecutionContext_nativeGetOutputByIndex
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnGraphExecutionContext
 * Method:    nativeGetOutputByName
 * Signature: (JLjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnGraphExecutionContext_nativeGetOutputByName
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnGraphExecutionContext
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnGraphExecutionContext_nativeClose
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
