/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiPollable */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiPollable
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiPollable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiPollable
 * Method:    nativeBlock
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiPollable_nativeBlock
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiPollable
 * Method:    nativeReady
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiPollable_nativeReady
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiPollable
 * Method:    nativeClose
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_io_JniWasiPollable_nativeClose
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
