/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniEngine */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniEngine
#define _Included_ai_tegmentum_wasmtime4j_jni_JniEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniEngine
 * Method:    nativeCreateStore
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniEngine_nativeCreateStore
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniEngine
 * Method:    nativeDestroyEngine
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniEngine_nativeDestroyEngine
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
