/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniGcRuntime */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniGcRuntime
#define _Included_ai_tegmentum_wasmtime4j_jni_JniGcRuntime
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGcRuntime
 * Method:    createRuntimeNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGcRuntime_createRuntimeNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGcRuntime
 * Method:    destroyRuntimeNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGcRuntime_destroyRuntimeNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGcRuntime
 * Method:    registerStructTypeNative
 * Signature: (JLjava/lang/String;[Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/Boolean;)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGcRuntime_registerStructTypeNative
  (JNIEnv *, jclass, jlong, jstring, jobjectArray, jobjectArray, jobjectArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGcRuntime
 * Method:    registerArrayTypeNative
 * Signature: (JLjava/lang/String;IZ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGcRuntime_registerArrayTypeNative
  (JNIEnv *, jclass, jlong, jstring, jint, jboolean);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGcRuntime
 * Method:    structNewNative
 * Signature: (JI[Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGcRuntime_structNewNative
  (JNIEnv *, jclass, jlong, jint, jobjectArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGcRuntime
 * Method:    structNewDefaultNative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGcRuntime_structNewDefaultNative
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGcRuntime
 * Method:    structGetNative
 * Signature: (JJI)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGcRuntime_structGetNative
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGcRuntime
 * Method:    structSetNative
 * Signature: (JJILjava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGcRuntime_structSetNative
  (JNIEnv *, jclass, jlong, jlong, jint, jobject);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGcRuntime
 * Method:    arrayNewNative
 * Signature: (JI[Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGcRuntime_arrayNewNative
  (JNIEnv *, jclass, jlong, jint, jobjectArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGcRuntime
 * Method:    arrayNewDefaultNative
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGcRuntime_arrayNewDefaultNative
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGcRuntime
 * Method:    arrayGetNative
 * Signature: (JJI)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGcRuntime_arrayGetNative
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGcRuntime
 * Method:    arraySetNative
 * Signature: (JJILjava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGcRuntime_arraySetNative
  (JNIEnv *, jclass, jlong, jlong, jint, jobject);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGcRuntime
 * Method:    arrayLenNative
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGcRuntime_arrayLenNative
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGcRuntime
 * Method:    i31NewNative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGcRuntime_i31NewNative
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGcRuntime
 * Method:    i31GetNative
 * Signature: (JJZ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGcRuntime_i31GetNative
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGcRuntime
 * Method:    refCastNative
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGcRuntime_refCastNative
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGcRuntime
 * Method:    refTestNative
 * Signature: (JJI)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGcRuntime_refTestNative
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGcRuntime
 * Method:    refEqNative
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGcRuntime_refEqNative
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGcRuntime
 * Method:    refIsNullNative
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGcRuntime_refIsNullNative
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGcRuntime
 * Method:    collectGarbageNative
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGcRuntime_collectGarbageNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGcRuntime
 * Method:    getGcStatsNative
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGcRuntime_getGcStatsNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGcRuntime
 * Method:    refCastStructNative
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGcRuntime_refCastStructNative
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGcRuntime
 * Method:    refCastArrayNative
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGcRuntime_refCastArrayNative
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGcRuntime
 * Method:    refTestStructNative
 * Signature: (JJI)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGcRuntime_refTestStructNative
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGcRuntime
 * Method:    refTestArrayNative
 * Signature: (JJI)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGcRuntime_refTestArrayNative
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGcRuntime
 * Method:    getRuntimeTypeNative
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGcRuntime_getRuntimeTypeNative
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGcRuntime
 * Method:    arrayCopyNative
 * Signature: (JJIJII)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGcRuntime_arrayCopyNative
  (JNIEnv *, jclass, jlong, jlong, jint, jlong, jint, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGcRuntime
 * Method:    arrayFillNative
 * Signature: (JJIILjava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGcRuntime_arrayFillNative
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
