/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniResolveAddressStream */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniResolveAddressStream
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniResolveAddressStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniResolveAddressStream
 * Method:    nativeGetNextAddress
 * Signature: (JJ)[I
 */
JNIEXPORT jintArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniResolveAddressStream_nativeGetNextAddress
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniResolveAddressStream
 * Method:    nativeSubscribe
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniResolveAddressStream_nativeSubscribe
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniResolveAddressStream
 * Method:    nativeIsClosed
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniResolveAddressStream_nativeIsClosed
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniResolveAddressStream
 * Method:    nativeClose
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniResolveAddressStream_nativeClose
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
