/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniProfiler */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniProfiler
#define _Included_ai_tegmentum_wasmtime4j_jni_JniProfiler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniProfiler
 * Method:    nativeProfilerCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniProfiler_nativeProfilerCreate
  (JNIEnv *, jclass);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniProfiler
 * Method:    nativeProfilerStart
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniProfiler_nativeProfilerStart
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniProfiler
 * Method:    nativeProfilerStop
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniProfiler_nativeProfilerStop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniProfiler
 * Method:    nativeProfilerIsProfiling
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniProfiler_nativeProfilerIsProfiling
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniProfiler
 * Method:    nativeProfilerRecordFunction
 * Signature: (JLjava/lang/String;JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniProfiler_nativeProfilerRecordFunction
  (JNIEnv *, jclass, jlong, jstring, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniProfiler
 * Method:    nativeProfilerRecordCompilation
 * Signature: (JJJZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniProfiler_nativeProfilerRecordCompilation
  (JNIEnv *, jclass, jlong, jlong, jlong, jboolean, jboolean);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniProfiler
 * Method:    nativeProfilerGetModulesCompiled
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniProfiler_nativeProfilerGetModulesCompiled
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniProfiler
 * Method:    nativeProfilerGetTotalCompilationTimeNanos
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniProfiler_nativeProfilerGetTotalCompilationTimeNanos
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniProfiler
 * Method:    nativeProfilerGetAverageCompilationTimeNanos
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniProfiler_nativeProfilerGetAverageCompilationTimeNanos
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniProfiler
 * Method:    nativeProfilerGetBytesCompiled
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniProfiler_nativeProfilerGetBytesCompiled
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniProfiler
 * Method:    nativeProfilerGetCacheHits
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniProfiler_nativeProfilerGetCacheHits
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniProfiler
 * Method:    nativeProfilerGetCacheMisses
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniProfiler_nativeProfilerGetCacheMisses
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniProfiler
 * Method:    nativeProfilerGetOptimizedModules
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniProfiler_nativeProfilerGetOptimizedModules
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniProfiler
 * Method:    nativeProfilerGetCurrentMemoryBytes
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniProfiler_nativeProfilerGetCurrentMemoryBytes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniProfiler
 * Method:    nativeProfilerGetPeakMemoryBytes
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniProfiler_nativeProfilerGetPeakMemoryBytes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniProfiler
 * Method:    nativeProfilerGetUptimeNanos
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniProfiler_nativeProfilerGetUptimeNanos
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniProfiler
 * Method:    nativeProfilerGetFunctionCallsPerSecond
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniProfiler_nativeProfilerGetFunctionCallsPerSecond
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniProfiler
 * Method:    nativeProfilerGetTotalFunctionCalls
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniProfiler_nativeProfilerGetTotalFunctionCalls
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniProfiler
 * Method:    nativeProfilerGetTotalExecutionTimeNanos
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniProfiler_nativeProfilerGetTotalExecutionTimeNanos
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniProfiler
 * Method:    nativeProfilerReset
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniProfiler_nativeProfilerReset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniProfiler
 * Method:    nativeProfilerDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniProfiler_nativeProfilerDestroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
