/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_memory_PlatformMemoryManager */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_memory_PlatformMemoryManager
#define _Included_ai_tegmentum_wasmtime4j_jni_memory_PlatformMemoryManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_memory_PlatformMemoryManager
 * Method:    nativeCreate
 * Signature: (ZIJJZZJZII)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_memory_PlatformMemoryManager_nativeCreate
  (JNIEnv *, jclass, jboolean, jint, jlong, jlong, jboolean, jboolean, jlong, jboolean, jint, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_memory_PlatformMemoryManager
 * Method:    nativeAllocate
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_memory_PlatformMemoryManager_nativeAllocate
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_memory_PlatformMemoryManager
 * Method:    nativeDeallocate
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_memory_PlatformMemoryManager_nativeDeallocate
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_memory_PlatformMemoryManager
 * Method:    nativeGetStats
 * Signature: (J)Lai/tegmentum/wasmtime4j/jni/memory/PlatformMemoryManager/MemoryStats;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_memory_PlatformMemoryManager_nativeGetStats
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_memory_PlatformMemoryManager
 * Method:    nativeGetPlatformInfo
 * Signature: (J)Lai/tegmentum/wasmtime4j/jni/memory/PlatformMemoryManager/PlatformInfo;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_memory_PlatformMemoryManager_nativeGetPlatformInfo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_memory_PlatformMemoryManager
 * Method:    nativeDetectLeaks
 * Signature: (J)[Lai/tegmentum/wasmtime4j/jni/memory/PlatformMemoryManager/MemoryLeak;
 */
JNIEXPORT jobjectArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_memory_PlatformMemoryManager_nativeDetectLeaks
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_memory_PlatformMemoryManager
 * Method:    nativePrefetch
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_memory_PlatformMemoryManager_nativePrefetch
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_memory_PlatformMemoryManager
 * Method:    nativeCompress
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_memory_PlatformMemoryManager_nativeCompress
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_memory_PlatformMemoryManager
 * Method:    nativeDeduplicate
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_memory_PlatformMemoryManager_nativeDeduplicate
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_memory_PlatformMemoryManager
 * Method:    nativeDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_memory_PlatformMemoryManager_nativeDestroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
