/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_WasiFilesystemSnapshot */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_WasiFilesystemSnapshot
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_WasiFilesystemSnapshot
#ifdef __cplusplus
extern "C" {
#endif
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiFilesystemSnapshot_MAX_SNAPSHOT_SIZE
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiFilesystemSnapshot_MAX_SNAPSHOT_SIZE 10737418240LL
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiFilesystemSnapshot_MAX_ACTIVE_SNAPSHOTS
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiFilesystemSnapshot_MAX_ACTIVE_SNAPSHOTS 100L
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiFilesystemSnapshot_MAX_INCREMENTAL_CHAIN_DEPTH
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiFilesystemSnapshot_MAX_INCREMENTAL_CHAIN_DEPTH 10L
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiFilesystemSnapshot
 * Method:    nativeInitSnapshotManager
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiFilesystemSnapshot_nativeInitSnapshotManager
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiFilesystemSnapshot
 * Method:    nativeCleanupSnapshotManager
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiFilesystemSnapshot_nativeCleanupSnapshotManager
  (JNIEnv *, jclass);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiFilesystemSnapshot
 * Method:    nativeCreateAdvancedSnapshot
 * Signature: (JJLjava/lang/String;IJZIZ[BZZLjava/lang/String;Ljava/lang/String;)Lai/tegmentum/wasmtime4j/jni/wasi/WasiFilesystemSnapshot/SnapshotCreateResult;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiFilesystemSnapshot_nativeCreateAdvancedSnapshot
  (JNIEnv *, jclass, jlong, jlong, jstring, jint, jlong, jboolean, jint, jboolean, jbyteArray, jboolean, jboolean, jstring, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiFilesystemSnapshot
 * Method:    nativeCreateSnapshot
 * Signature: (JJLjava/lang/String;ZJZIZ[B)Lai/tegmentum/wasmtime4j/jni/wasi/WasiFilesystemSnapshot/SnapshotCreateResult;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiFilesystemSnapshot_nativeCreateSnapshot
  (JNIEnv *, jclass, jlong, jlong, jstring, jboolean, jlong, jboolean, jint, jboolean, jbyteArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiFilesystemSnapshot
 * Method:    nativeRestoreSnapshot
 * Signature: (JJLjava/lang/String;ZZZZ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiFilesystemSnapshot_nativeRestoreSnapshot
  (JNIEnv *, jclass, jlong, jlong, jstring, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiFilesystemSnapshot
 * Method:    nativeVerifySnapshot
 * Signature: (JJ)Lai/tegmentum/wasmtime4j/jni/wasi/WasiFilesystemSnapshot/SnapshotVerifyResult;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiFilesystemSnapshot_nativeVerifySnapshot
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiFilesystemSnapshot
 * Method:    nativeDeleteSnapshot
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiFilesystemSnapshot_nativeDeleteSnapshot
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
