/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_type_JniImportDescriptor */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_type_JniImportDescriptor
#define _Included_ai_tegmentum_wasmtime4j_jni_type_JniImportDescriptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_type_JniImportDescriptor
 * Method:    nativeGetImportStringInfo
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_type_JniImportDescriptor_nativeGetImportStringInfo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_type_JniImportDescriptor
 * Method:    nativeGetImportTypeInfo
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_type_JniImportDescriptor_nativeGetImportTypeInfo
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
