/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_cli_JniWasiStdio */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_cli_JniWasiStdio
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_cli_JniWasiStdio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_cli_JniWasiStdio
 * Method:    nativeGetStdin
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_cli_JniWasiStdio_nativeGetStdin
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_cli_JniWasiStdio
 * Method:    nativeGetStdout
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_cli_JniWasiStdio_nativeGetStdout
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_cli_JniWasiStdio
 * Method:    nativeGetStderr
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_cli_JniWasiStdio_nativeGetStderr
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
