/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_http_JniWasiHttpContext */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_http_JniWasiHttpContext
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_http_JniWasiHttpContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_http_JniWasiHttpContext
 * Method:    nativeCreate
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;JJJIIJJZZZZZILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_http_JniWasiHttpContext_nativeCreate
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jlong, jlong, jlong, jint, jint, jlong, jlong, jboolean, jboolean, jboolean, jboolean, jboolean, jint, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_http_JniWasiHttpContext
 * Method:    nativeIsValid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_http_JniWasiHttpContext_nativeIsValid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_http_JniWasiHttpContext
 * Method:    nativeIsHostAllowed
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_http_JniWasiHttpContext_nativeIsHostAllowed
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_http_JniWasiHttpContext
 * Method:    nativeGetContextId
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_http_JniWasiHttpContext_nativeGetContextId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_http_JniWasiHttpContext
 * Method:    nativeResetStats
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_http_JniWasiHttpContext_nativeResetStats
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_http_JniWasiHttpContext
 * Method:    nativeFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_http_JniWasiHttpContext_nativeFree
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
