/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_WasiStreamOperations */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_WasiStreamOperations
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_WasiStreamOperations
#ifdef __cplusplus
extern "C" {
#endif
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiStreamOperations_MAX_BUFFER_SIZE
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiStreamOperations_MAX_BUFFER_SIZE 65536L
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiStreamOperations
 * Method:    nativeOpenInputStream
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiStreamOperations_nativeOpenInputStream
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiStreamOperations
 * Method:    nativeOpenOutputStream
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiStreamOperations_nativeOpenOutputStream
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiStreamOperations
 * Method:    nativeReadStream
 * Signature: (JJ[BI)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiStreamOperations_nativeReadStream
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiStreamOperations
 * Method:    nativeWriteStream
 * Signature: (JJ[BI)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiStreamOperations_nativeWriteStream
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiStreamOperations
 * Method:    nativeFlushStream
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiStreamOperations_nativeFlushStream
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiStreamOperations
 * Method:    nativeCloseStream
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiStreamOperations_nativeCloseStream
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
