/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiUdpSocket */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiUdpSocket
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiUdpSocket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiUdpSocket
 * Method:    nativeCreate
 * Signature: (JZ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiUdpSocket_nativeCreate
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiUdpSocket
 * Method:    nativeStartBind
 * Signature: (JJJZ[B[BIII)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiUdpSocket_nativeStartBind
  (JNIEnv *, jclass, jlong, jlong, jlong, jboolean, jbyteArray, jbyteArray, jint, jint, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiUdpSocket
 * Method:    nativeFinishBind
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiUdpSocket_nativeFinishBind
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiUdpSocket
 * Method:    nativeStream
 * Signature: (JJJZ[B[BIII)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiUdpSocket_nativeStream
  (JNIEnv *, jclass, jlong, jlong, jlong, jboolean, jbyteArray, jbyteArray, jint, jint, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiUdpSocket
 * Method:    nativeLocalAddress
 * Signature: (JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiUdpSocket_nativeLocalAddress
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiUdpSocket
 * Method:    nativeRemoteAddress
 * Signature: (JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiUdpSocket_nativeRemoteAddress
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiUdpSocket
 * Method:    nativeAddressFamily
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiUdpSocket_nativeAddressFamily
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiUdpSocket
 * Method:    nativeSetUnicastHopLimit
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiUdpSocket_nativeSetUnicastHopLimit
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiUdpSocket
 * Method:    nativeReceiveBufferSize
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiUdpSocket_nativeReceiveBufferSize
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiUdpSocket
 * Method:    nativeSetReceiveBufferSize
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiUdpSocket_nativeSetReceiveBufferSize
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiUdpSocket
 * Method:    nativeSendBufferSize
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiUdpSocket_nativeSendBufferSize
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiUdpSocket
 * Method:    nativeSetSendBufferSize
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiUdpSocket_nativeSetSendBufferSize
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiUdpSocket
 * Method:    nativeSubscribe
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiUdpSocket_nativeSubscribe
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiUdpSocket
 * Method:    nativeClose
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiUdpSocket_nativeClose
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
