/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_random_JniWasiRandom */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_random_JniWasiRandom
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_random_JniWasiRandom
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_random_JniWasiRandom
 * Method:    nativeGetRandomBytes
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_random_JniWasiRandom_nativeGetRandomBytes
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_random_JniWasiRandom
 * Method:    nativeGetRandomU64
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_random_JniWasiRandom_nativeGetRandomU64
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
