/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_experimental_JniExceptionHandlerImpl */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_experimental_JniExceptionHandlerImpl
#define _Included_ai_tegmentum_wasmtime4j_jni_experimental_JniExceptionHandlerImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_experimental_JniExceptionHandlerImpl
 * Method:    createNativeHandler
 * Signature: (Lai/tegmentum/wasmtime4j/experimental/ExceptionHandler/ExceptionHandlingConfig;)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_experimental_JniExceptionHandlerImpl_createNativeHandler
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_experimental_JniExceptionHandlerImpl
 * Method:    createNativeExceptionTag
 * Signature: (JLjava/lang/String;Ljava/util/List;)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_experimental_JniExceptionHandlerImpl_createNativeExceptionTag
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_experimental_JniExceptionHandlerImpl
 * Method:    captureNativeStackTrace
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_tegmentum_wasmtime4j_jni_experimental_JniExceptionHandlerImpl_captureNativeStackTrace
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_experimental_JniExceptionHandlerImpl
 * Method:    performNativeUnwinding
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_experimental_JniExceptionHandlerImpl_performNativeUnwinding
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_experimental_JniExceptionHandlerImpl
 * Method:    closeNativeHandler
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_experimental_JniExceptionHandlerImpl_closeNativeHandler
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
