/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniComponentEngine */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniComponentEngine
#define _Included_ai_tegmentum_wasmtime4j_jni_JniComponentEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponentEngine
 * Method:    nativeDetectPrecompiled
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponentEngine_nativeDetectPrecompiled
  (JNIEnv *, jobject, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
