/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_type_JniFuncType */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_type_JniFuncType
#define _Included_ai_tegmentum_wasmtime4j_jni_type_JniFuncType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_type_JniFuncType
 * Method:    nativeGetFuncTypeInfo
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_type_JniFuncType_nativeGetFuncTypeInfo
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
