/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniGlobal */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniGlobal
#define _Included_ai_tegmentum_wasmtime4j_jni_JniGlobal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGlobal
 * Method:    nativeGetValueType
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGlobal_nativeGetValueType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGlobal
 * Method:    nativeIsMutable
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGlobal_nativeIsMutable
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGlobal
 * Method:    nativeGetValue
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGlobal_nativeGetValue
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGlobal
 * Method:    nativeGetIntValue
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGlobal_nativeGetIntValue
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGlobal
 * Method:    nativeGetLongValue
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGlobal_nativeGetLongValue
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGlobal
 * Method:    nativeGetFloatValue
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGlobal_nativeGetFloatValue
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGlobal
 * Method:    nativeGetDoubleValue
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGlobal_nativeGetDoubleValue
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGlobal
 * Method:    nativeSetValue
 * Signature: (JLjava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGlobal_nativeSetValue
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGlobal
 * Method:    nativeSetIntValue
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGlobal_nativeSetIntValue
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGlobal
 * Method:    nativeSetLongValue
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGlobal_nativeSetLongValue
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGlobal
 * Method:    nativeSetFloatValue
 * Signature: (JF)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGlobal_nativeSetFloatValue
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGlobal
 * Method:    nativeSetDoubleValue
 * Signature: (JD)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGlobal_nativeSetDoubleValue
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGlobal
 * Method:    nativeDestroyGlobal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGlobal_nativeDestroyGlobal
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
