/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniFunction */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniFunction
#define _Included_ai_tegmentum_wasmtime4j_jni_JniFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniFunction
 * Method:    nativeGetParameterTypes
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniFunction_nativeGetParameterTypes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniFunction
 * Method:    nativeGetReturnTypes
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniFunction_nativeGetReturnTypes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniFunction
 * Method:    nativeCall
 * Signature: (JJ[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniFunction_nativeCall
  (JNIEnv *, jclass, jlong, jlong, jobjectArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniFunction
 * Method:    nativeCallMultiValue
 * Signature: (JJ[Ljava/lang/Object;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniFunction_nativeCallMultiValue
  (JNIEnv *, jclass, jlong, jlong, jobjectArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniFunction
 * Method:    nativeFuncToRaw
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniFunction_nativeFuncToRaw
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniFunction
 * Method:    nativeFuncFromRaw
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniFunction_nativeFuncFromRaw
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniFunction
 * Method:    nativeCallAsync
 * Signature: (JJ[Ljava/lang/Object;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniFunction_nativeCallAsync
  (JNIEnv *, jclass, jlong, jlong, jobjectArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniFunction
 * Method:    nativeFuncMatchesTy
 * Signature: (JJ[I[I)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniFunction_nativeFuncMatchesTy
  (JNIEnv *, jclass, jlong, jlong, jintArray, jintArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniFunction
 * Method:    nativeCall_V
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniFunction_nativeCall_1V
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniFunction
 * Method:    nativeCall_I
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniFunction_nativeCall_1I
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniFunction
 * Method:    nativeCallI_I
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniFunction_nativeCallI_1I
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniFunction
 * Method:    nativeCallII_I
 * Signature: (JJII)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniFunction_nativeCallII_1I
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniFunction
 * Method:    nativeCallI_V
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniFunction_nativeCallI_1V
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniFunction
 * Method:    nativeCallII_V
 * Signature: (JJII)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniFunction_nativeCallII_1V
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniFunction
 * Method:    nativeCallJ_J
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniFunction_nativeCallJ_1J
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniFunction
 * Method:    nativeCallD_D
 * Signature: (JJD)D
 */
JNIEXPORT jdouble JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniFunction_nativeCallD_1D
  (JNIEnv *, jclass, jlong, jlong, jdouble);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniFunction
 * Method:    nativeCallIII_I
 * Signature: (JJIII)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniFunction_nativeCallIII_1I
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
