/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniTypedFunc */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniTypedFunc
#define _Included_ai_tegmentum_wasmtime4j_jni_JniTypedFunc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTypedFunc
 * Method:    nativeCreate
 * Signature: (JJLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTypedFunc_nativeCreate
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTypedFunc
 * Method:    nativeCallVoidToVoid
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTypedFunc_nativeCallVoidToVoid
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTypedFunc
 * Method:    nativeCallI32ToVoid
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTypedFunc_nativeCallI32ToVoid
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTypedFunc
 * Method:    nativeCallI32I32ToVoid
 * Signature: (JJII)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTypedFunc_nativeCallI32I32ToVoid
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTypedFunc
 * Method:    nativeCallI64ToVoid
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTypedFunc_nativeCallI64ToVoid
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTypedFunc
 * Method:    nativeCallI64I64ToVoid
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTypedFunc_nativeCallI64I64ToVoid
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTypedFunc
 * Method:    nativeCallI32ToI32
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTypedFunc_nativeCallI32ToI32
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTypedFunc
 * Method:    nativeCallI32I32ToI32
 * Signature: (JJII)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTypedFunc_nativeCallI32I32ToI32
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTypedFunc
 * Method:    nativeCallI64ToI64
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTypedFunc_nativeCallI64ToI64
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTypedFunc
 * Method:    nativeCallI64I64ToI64
 * Signature: (JJJJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTypedFunc_nativeCallI64I64ToI64
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTypedFunc
 * Method:    nativeCallF32ToF32
 * Signature: (JJF)F
 */
JNIEXPORT jfloat JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTypedFunc_nativeCallF32ToF32
  (JNIEnv *, jclass, jlong, jlong, jfloat);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTypedFunc
 * Method:    nativeCallF64ToF64
 * Signature: (JJD)D
 */
JNIEXPORT jdouble JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTypedFunc_nativeCallF64ToF64
  (JNIEnv *, jclass, jlong, jlong, jdouble);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTypedFunc
 * Method:    nativeCallF32F32ToF32
 * Signature: (JJFF)F
 */
JNIEXPORT jfloat JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTypedFunc_nativeCallF32F32ToF32
  (JNIEnv *, jclass, jlong, jlong, jfloat, jfloat);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTypedFunc
 * Method:    nativeCallF64F64ToF64
 * Signature: (JJDD)D
 */
JNIEXPORT jdouble JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTypedFunc_nativeCallF64F64ToF64
  (JNIEnv *, jclass, jlong, jlong, jdouble, jdouble);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTypedFunc
 * Method:    nativeCallI32I32I32ToI32
 * Signature: (JJIII)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTypedFunc_nativeCallI32I32I32ToI32
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTypedFunc
 * Method:    nativeCallI64I64I64ToI64
 * Signature: (JJJJJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTypedFunc_nativeCallI64I64I64ToI64
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTypedFunc
 * Method:    nativeCallF32F32F32ToF32
 * Signature: (JJFFF)F
 */
JNIEXPORT jfloat JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTypedFunc_nativeCallF32F32F32ToF32
  (JNIEnv *, jclass, jlong, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTypedFunc
 * Method:    nativeCallF64F64F64ToF64
 * Signature: (JJDDD)D
 */
JNIEXPORT jdouble JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTypedFunc_nativeCallF64F64F64ToF64
  (JNIEnv *, jclass, jlong, jlong, jdouble, jdouble, jdouble);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTypedFunc
 * Method:    nativeCallI32I32ToI64
 * Signature: (JJII)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTypedFunc_nativeCallI32I32ToI64
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTypedFunc
 * Method:    nativeCallI64ToI32
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTypedFunc_nativeCallI64ToI32
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTypedFunc
 * Method:    nativeCallI32F32ToF32
 * Signature: (JJIF)F
 */
JNIEXPORT jfloat JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTypedFunc_nativeCallI32F32ToF32
  (JNIEnv *, jclass, jlong, jlong, jint, jfloat);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTypedFunc
 * Method:    nativeCallF32I32ToF32
 * Signature: (JJFI)F
 */
JNIEXPORT jfloat JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTypedFunc_nativeCallF32I32ToF32
  (JNIEnv *, jclass, jlong, jlong, jfloat, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniTypedFunc
 * Method:    nativeDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniTypedFunc_nativeDestroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
