/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniComponentLinker */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniComponentLinker
#define _Included_ai_tegmentum_wasmtime4j_jni_JniComponentLinker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponentLinker
 * Method:    nativeEnableWasiP2
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponentLinker_nativeEnableWasiP2
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponentLinker
 * Method:    nativeDestroyComponentLinker
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponentLinker_nativeDestroyComponentLinker
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponentLinker
 * Method:    nativeDefineHostFunction
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponentLinker_nativeDefineHostFunction
  (JNIEnv *, jobject, jlong, jstring, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponentLinker
 * Method:    nativeDefineResource
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;JJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponentLinker_nativeDefineResource
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponentLinker
 * Method:    nativeInstantiateWithLinker
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponentLinker_nativeInstantiateWithLinker
  (JNIEnv *, jobject, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
