/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_pool_JniPoolingAllocator */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_pool_JniPoolingAllocator
#define _Included_ai_tegmentum_wasmtime4j_jni_pool_JniPoolingAllocator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_pool_JniPoolingAllocator
 * Method:    nativeCreateWithConfig
 * Signature: (IJIIIIZZF)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_pool_JniPoolingAllocator_nativeCreateWithConfig
  (JNIEnv *, jclass, jint, jlong, jint, jint, jint, jint, jboolean, jboolean, jfloat);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_pool_JniPoolingAllocator
 * Method:    nativeCreateFromJsonConfig
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_pool_JniPoolingAllocator_nativeCreateFromJsonConfig
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_pool_JniPoolingAllocator
 * Method:    nativeAllocateInstance
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_pool_JniPoolingAllocator_nativeAllocateInstance
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_pool_JniPoolingAllocator
 * Method:    nativeReuseInstance
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_pool_JniPoolingAllocator_nativeReuseInstance
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_pool_JniPoolingAllocator
 * Method:    nativeReleaseInstance
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_pool_JniPoolingAllocator_nativeReleaseInstance
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_pool_JniPoolingAllocator
 * Method:    nativeGetStatistics
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_pool_JniPoolingAllocator_nativeGetStatistics
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_pool_JniPoolingAllocator
 * Method:    nativeResetStatistics
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_pool_JniPoolingAllocator_nativeResetStatistics
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_pool_JniPoolingAllocator
 * Method:    nativeWarmPools
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_pool_JniPoolingAllocator_nativeWarmPools
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_pool_JniPoolingAllocator
 * Method:    nativePerformMaintenance
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_pool_JniPoolingAllocator_nativePerformMaintenance
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_pool_JniPoolingAllocator
 * Method:    nativeDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_pool_JniPoolingAllocator_nativeDestroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
