/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations
#ifdef __cplusplus
extern "C" {
#endif
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_PROTOCOL_WEBSOCKET
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_PROTOCOL_WEBSOCKET 1L
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_PROTOCOL_HTTP2
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_PROTOCOL_HTTP2 2L
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_PROTOCOL_GRPC
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_PROTOCOL_GRPC 3L
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_WS_MESSAGE_TEXT
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_WS_MESSAGE_TEXT 1L
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_WS_MESSAGE_BINARY
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_WS_MESSAGE_BINARY 2L
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_WS_MESSAGE_PING
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_WS_MESSAGE_PING 9L
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_WS_MESSAGE_PONG
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_WS_MESSAGE_PONG 10L
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_WS_MESSAGE_CLOSE
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_WS_MESSAGE_CLOSE 8L
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_HTTP2_STREAM_IDLE
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_HTTP2_STREAM_IDLE 0L
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_HTTP2_STREAM_OPEN
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_HTTP2_STREAM_OPEN 1L
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_HTTP2_STREAM_RESERVED_LOCAL
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_HTTP2_STREAM_RESERVED_LOCAL 2L
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_HTTP2_STREAM_RESERVED_REMOTE
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_HTTP2_STREAM_RESERVED_REMOTE 3L
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_HTTP2_STREAM_HALF_CLOSED_LOCAL
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_HTTP2_STREAM_HALF_CLOSED_LOCAL 4L
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_HTTP2_STREAM_HALF_CLOSED_REMOTE
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_HTTP2_STREAM_HALF_CLOSED_REMOTE 5L
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_HTTP2_STREAM_CLOSED
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_HTTP2_STREAM_CLOSED 6L
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations
 * Method:    nativeInitializeAdvancedNetworking
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_nativeInitializeAdvancedNetworking
  (JNIEnv *, jclass);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations
 * Method:    nativeWebSocketConnect
 * Signature: (Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;JJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_nativeWebSocketConnect
  (JNIEnv *, jclass, jstring, jobjectArray, jobjectArray, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations
 * Method:    nativeWebSocketSend
 * Signature: (JILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_nativeWebSocketSend
  (JNIEnv *, jclass, jlong, jint, jobject, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations
 * Method:    nativeWebSocketReceive
 * Signature: (JLjava/nio/ByteBuffer;IJ[I[I)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_nativeWebSocketReceive
  (JNIEnv *, jclass, jlong, jobject, jint, jlong, jintArray, jintArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations
 * Method:    nativeHttp2Connect
 * Signature: (Ljava/lang/String;IIJJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_nativeHttp2Connect
  (JNIEnv *, jclass, jstring, jint, jint, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations
 * Method:    nativeGrpcConnect
 * Signature: (Ljava/lang/String;IJJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_nativeGrpcConnect
  (JNIEnv *, jclass, jstring, jint, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations
 * Method:    nativeCloseConnection
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_nativeCloseConnection
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations
 * Method:    nativeCleanupAdvancedNetworking
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiAdvancedNetworkOperations_nativeCleanupAdvancedNetworking
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
