/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniDebugger */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniDebugger
#define _Included_ai_tegmentum_wasmtime4j_jni_JniDebugger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniDebugger
 * Method:    nativeCreateDebugger
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniDebugger_nativeCreateDebugger
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniDebugger
 * Method:    nativeCloseDebugger
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniDebugger_nativeCloseDebugger
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniDebugger
 * Method:    nativeIsValidDebugger
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniDebugger_nativeIsValidDebugger
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniDebugger
 * Method:    nativeGetCapabilities
 * Signature: (J)Lai/tegmentum/wasmtime4j/debug/DebugCapabilities;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniDebugger_nativeGetCapabilities
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniDebugger
 * Method:    nativeAttachToInstance
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniDebugger_nativeAttachToInstance
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniDebugger
 * Method:    nativeDetachFromInstance
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniDebugger_nativeDetachFromInstance
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniDebugger
 * Method:    nativeGetDebugInfo
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniDebugger_nativeGetDebugInfo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniDebugger
 * Method:    nativeSetDebugModeEnabled
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniDebugger_nativeSetDebugModeEnabled
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniDebugger
 * Method:    nativeIsDebugModeEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniDebugger_nativeIsDebugModeEnabled
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniDebugger
 * Method:    nativeSetDebugOptions
 * Signature: (JLai/tegmentum/wasmtime4j/debug/DebugOptions;)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniDebugger_nativeSetDebugOptions
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniDebugger
 * Method:    nativeGetDebugOptions
 * Signature: (J)Lai/tegmentum/wasmtime4j/debug/DebugOptions;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniDebugger_nativeGetDebugOptions
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniDebugger
 * Method:    nativeGetDwarfInfo
 * Signature: (JJ)Lai/tegmentum/wasmtime4j/jni/JniDebugger/DwarfDebugInfo;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniDebugger_nativeGetDwarfInfo
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniDebugger
 * Method:    nativeCreateSourceMapIntegration
 * Signature: (JLjava/lang/String;)Lai/tegmentum/wasmtime4j/jni/JniDebugger/SourceMapIntegration;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniDebugger_nativeCreateSourceMapIntegration
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniDebugger
 * Method:    nativeCreateExecutionTracer
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniDebugger_nativeCreateExecutionTracer
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniDebugger
 * Method:    nativeStartProfiling
 * Signature: (JZZ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniDebugger_nativeStartProfiling
  (JNIEnv *, jclass, jlong, jboolean, jboolean);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniDebugger
 * Method:    nativeStopProfiling
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniDebugger_nativeStopProfiling
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniDebugger
 * Method:    nativeGetProfilingData
 * Signature: (J)Lai/tegmentum/wasmtime4j/jni/JniDebugger/ProfilingData;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniDebugger_nativeGetProfilingData
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniDebugger
 * Method:    nativeSetBreakpointAtAddress
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniDebugger_nativeSetBreakpointAtAddress
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniDebugger
 * Method:    nativeSetBreakpointAtFunction
 * Signature: (JJLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniDebugger_nativeSetBreakpointAtFunction
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniDebugger
 * Method:    nativeSetBreakpointAtLine
 * Signature: (JJLjava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniDebugger_nativeSetBreakpointAtLine
  (JNIEnv *, jclass, jlong, jlong, jstring, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniDebugger
 * Method:    nativeRemoveBreakpoint
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniDebugger_nativeRemoveBreakpoint
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniDebugger
 * Method:    nativeGetCallStack
 * Signature: (JJ)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniDebugger_nativeGetCallStack
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniDebugger
 * Method:    nativeGetLocalVariables
 * Signature: (JJI)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniDebugger_nativeGetLocalVariables
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniDebugger
 * Method:    nativeEvaluateExpression
 * Signature: (JJLjava/lang/String;)Lai/tegmentum/wasmtime4j/jni/debug/JniVariableValue;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniDebugger_nativeEvaluateExpression
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniDebugger
 * Method:    nativeInspectMemory
 * Signature: (JJII)Lai/tegmentum/wasmtime4j/jni/JniDebugger/MemoryInfo;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniDebugger_nativeInspectMemory
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniDebugger
 * Method:    nativeStepInto
 * Signature: (JJ)Lai/tegmentum/wasmtime4j/jni/JniDebugger/ExecutionResult;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniDebugger_nativeStepInto
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniDebugger
 * Method:    nativeStepOver
 * Signature: (JJ)Lai/tegmentum/wasmtime4j/jni/JniDebugger/ExecutionResult;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniDebugger_nativeStepOver
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniDebugger
 * Method:    nativeStepOut
 * Signature: (JJ)Lai/tegmentum/wasmtime4j/jni/JniDebugger/ExecutionResult;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniDebugger_nativeStepOut
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniDebugger
 * Method:    nativeContinue
 * Signature: (JJ)Lai/tegmentum/wasmtime4j/jni/JniDebugger/ExecutionResult;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniDebugger_nativeContinue
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniDebugger
 * Method:    nativeEnableDwarf
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniDebugger_nativeEnableDwarf
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniDebugger
 * Method:    nativeIsDwarfEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniDebugger_nativeIsDwarfEnabled
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
