/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniWitInterfaceEvolution */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniWitInterfaceEvolution
#define _Included_ai_tegmentum_wasmtime4j_jni_JniWitInterfaceEvolution
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWitInterfaceEvolution
 * Method:    nativeCreateEvolutionManager
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWitInterfaceEvolution_nativeCreateEvolutionManager
  (JNIEnv *, jclass);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWitInterfaceEvolution
 * Method:    nativeDestroyEvolutionManager
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWitInterfaceEvolution_nativeDestroyEvolutionManager
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWitInterfaceEvolution
 * Method:    nativeAnalyzeEvolution
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWitInterfaceEvolution_nativeAnalyzeEvolution
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWitInterfaceEvolution
 * Method:    nativeCheckBackwardCompatibility
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWitInterfaceEvolution_nativeCheckBackwardCompatibility
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWitInterfaceEvolution
 * Method:    nativeCheckForwardCompatibility
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWitInterfaceEvolution_nativeCheckForwardCompatibility
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWitInterfaceEvolution
 * Method:    nativeCreateAdapter
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWitInterfaceEvolution_nativeCreateAdapter
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWitInterfaceEvolution
 * Method:    nativeValidateEvolutionStrategy
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWitInterfaceEvolution_nativeValidateEvolutionStrategy
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWitInterfaceEvolution
 * Method:    nativeCreateMigrationPlan
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWitInterfaceEvolution_nativeCreateMigrationPlan
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWitInterfaceEvolution
 * Method:    nativeExecuteMigration
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWitInterfaceEvolution_nativeExecuteMigration
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWitInterfaceEvolution
 * Method:    nativeGetEvolutionHistory
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWitInterfaceEvolution_nativeGetEvolutionHistory
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWitInterfaceEvolution
 * Method:    nativeRegisterInterfaceVersion
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWitInterfaceEvolution_nativeRegisterInterfaceVersion
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWitInterfaceEvolution
 * Method:    nativeDeprecateInterfaceVersion
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWitInterfaceEvolution_nativeDeprecateInterfaceVersion
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWitInterfaceEvolution
 * Method:    nativeGetInterfaceVersions
 * Signature: (JLjava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWitInterfaceEvolution_nativeGetInterfaceVersions
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWitInterfaceEvolution
 * Method:    nativeFindCompatibleVersion
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWitInterfaceEvolution_nativeFindCompatibleVersion
  (JNIEnv *, jclass, jlong, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
