/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_type_JniTableType */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_type_JniTableType
#define _Included_ai_tegmentum_wasmtime4j_jni_type_JniTableType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_type_JniTableType
 * Method:    nativeGetTableTypeInfo
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_type_JniTableType_nativeGetTableTypeInfo
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
