/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations
#ifdef __cplusplus
extern "C" {
#endif
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations_MAX_ASYNC_OPERATIONS
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations_MAX_ASYNC_OPERATIONS 1000L
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations
 * Method:    nativeCreateResource
 * Signature: (JJLjava/lang/String;Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations_nativeCreateResource
  (JNIEnv *, jclass, jlong, jlong, jstring, jobject, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations
 * Method:    nativeDestroyResource
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations_nativeDestroyResource
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations
 * Method:    nativePoll
 * Signature: (J[JJ)[I
 */
JNIEXPORT jintArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations_nativePoll
  (JNIEnv *, jclass, jlong, jlongArray, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations
 * Method:    nativeCompileComponent
 * Signature: (JLjava/nio/ByteBuffer;I)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations_nativeCompileComponent
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations
 * Method:    nativeInstantiateComponent
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations_nativeInstantiateComponent
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations
 * Method:    nativeCreateInputStream
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations_nativeCreateInputStream
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations
 * Method:    nativeCreateOutputStream
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations_nativeCreateOutputStream
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations
 * Method:    nativeStreamRead
 * Signature: (JJJLjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations_nativeStreamRead
  (JNIEnv *, jclass, jlong, jlong, jlong, jobject, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations
 * Method:    nativeStreamWrite
 * Signature: (JJJLjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations_nativeStreamWrite
  (JNIEnv *, jclass, jlong, jlong, jlong, jobject, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations
 * Method:    nativeCloseStream
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations_nativeCloseStream
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations
 * Method:    nativeGetOperationStatus
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations_nativeGetOperationStatus
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations
 * Method:    nativeCancelOperation
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations_nativeCancelOperation
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations
 * Method:    nativeCleanupOperations
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations_nativeCleanupOperations
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations
 * Method:    nativeGetOperationCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations_nativeGetOperationCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations
 * Method:    nativeNetworkingEnabled
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations_nativeNetworkingEnabled
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations
 * Method:    nativeFilesystemEnabled
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations_nativeFilesystemEnabled
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations
 * Method:    nativeProcessEnabled
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations_nativeProcessEnabled
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations
 * Method:    nativeGetComponentCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations_nativeGetComponentCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations
 * Method:    nativeGetInstanceCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiPreview2Operations_nativeGetInstanceCount
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
