/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnContextFactory */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnContextFactory
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnContextFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnContextFactory
 * Method:    nativeIsFeatureEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnContextFactory_nativeIsFeatureEnabled
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
