/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_type_JniMemoryType */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_type_JniMemoryType
#define _Included_ai_tegmentum_wasmtime4j_jni_type_JniMemoryType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_type_JniMemoryType
 * Method:    nativeGetMemoryTypeInfo
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_type_JniMemoryType_nativeGetMemoryTypeInfo
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
