/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_WasiRandomOperations */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_WasiRandomOperations
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_WasiRandomOperations
#ifdef __cplusplus
extern "C" {
#endif
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiRandomOperations_MAX_BUFFER_SIZE
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiRandomOperations_MAX_BUFFER_SIZE 1048576L
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiRandomOperations
 * Method:    nativeGetRandomBytesDirect
 * Signature: (JLjava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiRandomOperations_nativeGetRandomBytesDirect
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiRandomOperations
 * Method:    nativeGetRandomBytesArray
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiRandomOperations_nativeGetRandomBytesArray
  (JNIEnv *, jclass, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
