/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_debug_JniDebugSession */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_debug_JniDebugSession
#define _Included_ai_tegmentum_wasmtime4j_jni_debug_JniDebugSession
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_debug_JniDebugSession
 * Method:    nativeStart
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_debug_JniDebugSession_nativeStart
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_debug_JniDebugSession
 * Method:    nativeStop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_debug_JniDebugSession_nativeStop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_debug_JniDebugSession
 * Method:    nativeStep
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_debug_JniDebugSession_nativeStep
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_debug_JniDebugSession
 * Method:    nativeContinue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_debug_JniDebugSession_nativeContinue
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_debug_JniDebugSession
 * Method:    nativeAddBreakpoint
 * Signature: (JLjava/lang/String;IIJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_debug_JniDebugSession_nativeAddBreakpoint
  (JNIEnv *, jclass, jlong, jstring, jint, jint, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_debug_JniDebugSession
 * Method:    nativeRemoveBreakpoint
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_debug_JniDebugSession_nativeRemoveBreakpoint
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
