/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniMemory */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniMemory
#define _Included_ai_tegmentum_wasmtime4j_jni_JniMemory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeGetSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeGetSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeGrow
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeGrow
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeReadByte
 * Signature: (JJ)B
 */
JNIEXPORT jbyte JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeReadByte
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeWriteByte
 * Signature: (JJB)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeWriteByte
  (JNIEnv *, jclass, jlong, jlong, jbyte);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeReadBytes
 * Signature: (JJ[B)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeReadBytes
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeWriteBytes
 * Signature: (JJ[B)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeWriteBytes
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeGetBuffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeGetBuffer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniMemory
 * Method:    nativeDestroyMemory
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniMemory_nativeDestroyMemory
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
