/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniWitValueMarshaller */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniWitValueMarshaller
#define _Included_ai_tegmentum_wasmtime4j_jni_JniWitValueMarshaller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWitValueMarshaller
 * Method:    witValueSerializeNative
 * Signature: (I[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWitValueMarshaller_witValueSerializeNative
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWitValueMarshaller
 * Method:    witValueDeserializeNative
 * Signature: (I[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWitValueMarshaller_witValueDeserializeNative
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWitValueMarshaller
 * Method:    witValueValidateDiscriminatorNative
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWitValueMarshaller_witValueValidateDiscriminatorNative
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
