/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniEngine */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniEngine
#define _Included_ai_tegmentum_wasmtime4j_jni_JniEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniEngine
 * Method:    nativeCompileModule
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniEngine_nativeCompileModule
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniEngine
 * Method:    nativeCompileWat
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniEngine_nativeCompileWat
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniEngine
 * Method:    nativePrecompileModule
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniEngine_nativePrecompileModule
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniEngine
 * Method:    nativeCreateStore
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniEngine_nativeCreateStore
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniEngine
 * Method:    nativeDestroyEngine
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniEngine_nativeDestroyEngine
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniEngine
 * Method:    nativeIsEpochInterruptionEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniEngine_nativeIsEpochInterruptionEnabled
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniEngine
 * Method:    nativeIsCoredumpOnTrapEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniEngine_nativeIsCoredumpOnTrapEnabled
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniEngine
 * Method:    nativeIsFuelEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniEngine_nativeIsFuelEnabled
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniEngine
 * Method:    nativeGetStackSizeLimit
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniEngine_nativeGetStackSizeLimit
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniEngine
 * Method:    nativeGetMemoryLimitPages
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniEngine_nativeGetMemoryLimitPages
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniEngine
 * Method:    nativeSupportsFeature
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniEngine_nativeSupportsFeature
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniEngine
 * Method:    nativeIsPulley
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniEngine_nativeIsPulley
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniEngine
 * Method:    nativePrecompileCompatibilityHash
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniEngine_nativePrecompileCompatibilityHash
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniEngine
 * Method:    nativeDetectPrecompiled
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniEngine_nativeDetectPrecompiled
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniEngine
 * Method:    nativeEngineSame
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniEngine_nativeEngineSame
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniEngine
 * Method:    nativeIsAsync
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniEngine_nativeIsAsync
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniEngine
 * Method:    nativeIncrementEpoch
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniEngine_nativeIncrementEpoch
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniEngine
 * Method:    nativeCreateEngineWithExtendedConfig
 * Signature: (IIZZZZZZZIIZIZZZZJJJZZZZZZZZZZ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniEngine_nativeCreateEngineWithExtendedConfig
  (JNIEnv *, jclass, jint, jint, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jint, jint, jboolean, jint, jboolean, jboolean, jboolean, jboolean, jlong, jlong, jlong, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniEngine
 * Method:    nativeClearHandleRegistries
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniEngine_nativeClearHandleRegistries
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
