/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_keyvalue_JniWasiKeyValue */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_keyvalue_JniWasiKeyValue
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_keyvalue_JniWasiKeyValue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_keyvalue_JniWasiKeyValue
 * Method:    nativeCreateContext
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_keyvalue_JniWasiKeyValue_nativeCreateContext
  (JNIEnv *, jclass);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_keyvalue_JniWasiKeyValue
 * Method:    nativeDestroyContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_keyvalue_JniWasiKeyValue_nativeDestroyContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_keyvalue_JniWasiKeyValue
 * Method:    nativeGet
 * Signature: (JLjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_keyvalue_JniWasiKeyValue_nativeGet
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_keyvalue_JniWasiKeyValue
 * Method:    nativeSet
 * Signature: (JLjava/lang/String;[B)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_keyvalue_JniWasiKeyValue_nativeSet
  (JNIEnv *, jclass, jlong, jstring, jbyteArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_keyvalue_JniWasiKeyValue
 * Method:    nativeDelete
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_keyvalue_JniWasiKeyValue_nativeDelete
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_keyvalue_JniWasiKeyValue
 * Method:    nativeExists
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_keyvalue_JniWasiKeyValue_nativeExists
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_keyvalue_JniWasiKeyValue
 * Method:    nativeKeys
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_keyvalue_JniWasiKeyValue_nativeKeys
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_keyvalue_JniWasiKeyValue
 * Method:    nativeIsAvailable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_keyvalue_JniWasiKeyValue_nativeIsAvailable
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
