/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnGraph */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnGraph
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnGraph
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnGraph
 * Method:    nativeGetEncoding
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnGraph_nativeGetEncoding
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnGraph
 * Method:    nativeGetTarget
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnGraph_nativeGetTarget
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnGraph
 * Method:    nativeCreateExecCtx
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnGraph_nativeCreateExecCtx
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnGraph
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_nn_JniNnGraph_nativeClose
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
