/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniExnRef */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniExnRef
#define _Included_ai_tegmentum_wasmtime4j_jni_JniExnRef
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniExnRef
 * Method:    nativeGetTag
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniExnRef_nativeGetTag
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniExnRef
 * Method:    nativeIsValid
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniExnRef_nativeIsValid
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniExnRef
 * Method:    nativeGetField
 * Signature: (JJI)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniExnRef_nativeGetField
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniExnRef
 * Method:    nativeGetFields
 * Signature: (JJ)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniExnRef_nativeGetFields
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniExnRef
 * Method:    nativeCreate
 * Signature: (JJ[I[J[D[B)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniExnRef_nativeCreate
  (JNIEnv *, jclass, jlong, jlong, jintArray, jlongArray, jdoubleArray, jbyteArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniExnRef
 * Method:    nativeToRaw
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniExnRef_nativeToRaw
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniExnRef
 * Method:    nativeFromRaw
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniExnRef_nativeFromRaw
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniExnRef
 * Method:    nativeMatchesTy
 * Signature: (JJI)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniExnRef_nativeMatchesTy
  (JNIEnv *, jclass, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
