/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniGuestProfiler */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniGuestProfiler
#define _Included_ai_tegmentum_wasmtime4j_jni_JniGuestProfiler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGuestProfiler
 * Method:    nativeGuestProfilerCreate
 * Signature: (JLjava/lang/String;J[J[Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGuestProfiler_nativeGuestProfilerCreate
  (JNIEnv *, jclass, jlong, jstring, jlong, jlongArray, jobjectArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGuestProfiler
 * Method:    nativeGuestProfilerSample
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGuestProfiler_nativeGuestProfilerSample
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGuestProfiler
 * Method:    nativeGuestProfilerCallHook
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGuestProfiler_nativeGuestProfilerCallHook
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGuestProfiler
 * Method:    nativeGuestProfilerFinish
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGuestProfiler_nativeGuestProfilerFinish
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniGuestProfiler
 * Method:    nativeGuestProfilerDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniGuestProfiler_nativeGuestProfilerDestroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
