/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniWasmRuntime */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniWasmRuntime
#define _Included_ai_tegmentum_wasmtime4j_jni_JniWasmRuntime
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasmRuntime
 * Method:    nativeCreateRuntime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasmRuntime_nativeCreateRuntime
  (JNIEnv *, jclass);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasmRuntime
 * Method:    nativeCreateEngine
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasmRuntime_nativeCreateEngine
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasmRuntime
 * Method:    nativeCompileModule
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasmRuntime_nativeCompileModule
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasmRuntime
 * Method:    nativeGetWasmtimeVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasmRuntime_nativeGetWasmtimeVersion
  (JNIEnv *, jclass);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniWasmRuntime
 * Method:    nativeDestroyRuntime
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniWasmRuntime_nativeDestroyRuntime
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
