/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_clocks_JniWasiWallClock */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_clocks_JniWasiWallClock
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_clocks_JniWasiWallClock
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_clocks_JniWasiWallClock
 * Method:    nativeNow
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_clocks_JniWasiWallClock_nativeNow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_clocks_JniWasiWallClock
 * Method:    nativeResolution
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_clocks_JniWasiWallClock_nativeResolution
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
