/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniLinker */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniLinker
#define _Included_ai_tegmentum_wasmtime4j_jni_JniLinker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniLinker
 * Method:    nativeDefineHostFunction
 * Signature: (JLjava/lang/String;Ljava/lang/String;[I[IJ)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniLinker_nativeDefineHostFunction
  (JNIEnv *, jobject, jlong, jstring, jstring, jintArray, jintArray, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniLinker
 * Method:    nativeDefineHostFunctionUnchecked
 * Signature: (JLjava/lang/String;Ljava/lang/String;[I[IJ)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniLinker_nativeDefineHostFunctionUnchecked
  (JNIEnv *, jobject, jlong, jstring, jstring, jintArray, jintArray, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniLinker
 * Method:    nativeDefineMemory
 * Signature: (JJLjava/lang/String;Ljava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniLinker_nativeDefineMemory
  (JNIEnv *, jobject, jlong, jlong, jstring, jstring, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniLinker
 * Method:    nativeDefineTable
 * Signature: (JJLjava/lang/String;Ljava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniLinker_nativeDefineTable
  (JNIEnv *, jobject, jlong, jlong, jstring, jstring, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniLinker
 * Method:    nativeDefineGlobal
 * Signature: (JJLjava/lang/String;Ljava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniLinker_nativeDefineGlobal
  (JNIEnv *, jobject, jlong, jlong, jstring, jstring, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniLinker
 * Method:    nativeDefineInstance
 * Signature: (JJLjava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniLinker_nativeDefineInstance
  (JNIEnv *, jobject, jlong, jlong, jstring, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniLinker
 * Method:    nativeInstantiate
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniLinker_nativeInstantiate
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniLinker
 * Method:    nativeInstantiateNamed
 * Signature: (JJLjava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniLinker_nativeInstantiateNamed
  (JNIEnv *, jobject, jlong, jlong, jstring, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniLinker
 * Method:    nativeInstantiatePre
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniLinker_nativeInstantiatePre
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniLinker
 * Method:    nativeAlias
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniLinker_nativeAlias
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniLinker
 * Method:    nativeAliasModule
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniLinker_nativeAliasModule
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniLinker
 * Method:    nativeEnableWasi
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniLinker_nativeEnableWasi
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniLinker
 * Method:    nativeDestroyLinker
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniLinker_nativeDestroyLinker
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniLinker
 * Method:    nativeAllowShadowing
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniLinker_nativeAllowShadowing
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniLinker
 * Method:    nativeAllowUnknownExports
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniLinker_nativeAllowUnknownExports
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniLinker
 * Method:    nativeDefineUnknownImportsAsTraps
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniLinker_nativeDefineUnknownImportsAsTraps
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniLinker
 * Method:    nativeDefineUnknownImportsAsDefaultValues
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniLinker_nativeDefineUnknownImportsAsDefaultValues
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniLinker
 * Method:    nativeGetByImport
 * Signature: (JJLjava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniLinker_nativeGetByImport
  (JNIEnv *, jobject, jlong, jlong, jstring, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniLinker
 * Method:    nativeGetDefault
 * Signature: (JJLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniLinker_nativeGetDefault
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniLinker
 * Method:    nativeLinkerIter
 * Signature: (JJ)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniLinker_nativeLinkerIter
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniLinker
 * Method:    nativeGetExternType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniLinker_nativeGetExternType
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniLinker
 * Method:    nativeDefineName
 * Signature: (JJLjava/lang/String;JI)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniLinker_nativeDefineName
  (JNIEnv *, jobject, jlong, jlong, jstring, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniLinker
 * Method:    nativeDefine
 * Signature: (JJLjava/lang/String;Ljava/lang/String;JI)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniLinker_nativeDefine
  (JNIEnv *, jobject, jlong, jlong, jstring, jstring, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniLinker
 * Method:    nativeModule
 * Signature: (JJLjava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniLinker_nativeModule
  (JNIEnv *, jobject, jlong, jlong, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
