/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniComponentImpl */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniComponentImpl
#define _Included_ai_tegmentum_wasmtime4j_jni_JniComponentImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponentImpl
 * Method:    nativeGetComponentsLoaded
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponentImpl_nativeGetComponentsLoaded
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponentImpl
 * Method:    nativeGetInstancesCreated
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponentImpl_nativeGetInstancesCreated
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponentImpl
 * Method:    nativeGetInstancesDestroyed
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponentImpl_nativeGetInstancesDestroyed
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponentImpl
 * Method:    nativeGetAvgInstantiationTimeNanos
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponentImpl_nativeGetAvgInstantiationTimeNanos
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponentImpl
 * Method:    nativeGetPeakMemoryUsage
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponentImpl_nativeGetPeakMemoryUsage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponentImpl
 * Method:    nativeGetFunctionCalls
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponentImpl_nativeGetFunctionCalls
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponentImpl
 * Method:    nativeGetErrorCount
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponentImpl_nativeGetErrorCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponentImpl
 * Method:    nativeGetMetrics
 * Signature: (J)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponentImpl_nativeGetMetrics
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
