/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniLinker */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniLinker
#define _Included_ai_tegmentum_wasmtime4j_jni_JniLinker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniLinker
 * Method:    nativeDestroyLinker
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniLinker_nativeDestroyLinker
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
