/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniExperimentalFeatures */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniExperimentalFeatures
#define _Included_ai_tegmentum_wasmtime4j_jni_JniExperimentalFeatures
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniExperimentalFeatures
 * Method:    nativeCreateExperimentalConfig
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniExperimentalFeatures_nativeCreateExperimentalConfig
  (JNIEnv *, jclass);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniExperimentalFeatures
 * Method:    nativeCreateAllExperimentalConfig
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniExperimentalFeatures_nativeCreateAllExperimentalConfig
  (JNIEnv *, jclass);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniExperimentalFeatures
 * Method:    nativeEnableStackSwitching
 * Signature: (JJI)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniExperimentalFeatures_nativeEnableStackSwitching
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniExperimentalFeatures
 * Method:    nativeEnableCallCc
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniExperimentalFeatures_nativeEnableCallCc
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniExperimentalFeatures
 * Method:    nativeEnableExtendedConstExpressions
 * Signature: (JZZI)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniExperimentalFeatures_nativeEnableExtendedConstExpressions
  (JNIEnv *, jclass, jlong, jboolean, jboolean, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniExperimentalFeatures
 * Method:    nativeApplyExperimentalFeatures
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniExperimentalFeatures_nativeApplyExperimentalFeatures
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniExperimentalFeatures
 * Method:    nativeDestroyExperimentalConfig
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniExperimentalFeatures_nativeDestroyExperimentalConfig
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniExperimentalFeatures
 * Method:    nativeEnableFlexibleVectors
 * Signature: (JZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniExperimentalFeatures_nativeEnableFlexibleVectors
  (JNIEnv *, jclass, jlong, jboolean, jboolean, jboolean);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniExperimentalFeatures
 * Method:    nativeEnableStringImports
 * Signature: (JIZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniExperimentalFeatures_nativeEnableStringImports
  (JNIEnv *, jclass, jlong, jint, jboolean, jboolean, jboolean);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniExperimentalFeatures
 * Method:    nativeEnableResourceTypes
 * Signature: (JZZI)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniExperimentalFeatures_nativeEnableResourceTypes
  (JNIEnv *, jclass, jlong, jboolean, jboolean, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniExperimentalFeatures
 * Method:    nativeEnableTypeImports
 * Signature: (JIIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniExperimentalFeatures_nativeEnableTypeImports
  (JNIEnv *, jclass, jlong, jint, jint, jboolean);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniExperimentalFeatures
 * Method:    nativeEnableSharedEverythingThreads
 * Signature: (JIIZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniExperimentalFeatures_nativeEnableSharedEverythingThreads
  (JNIEnv *, jclass, jlong, jint, jint, jboolean, jboolean);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniExperimentalFeatures
 * Method:    nativeEnableCustomPageSizes
 * Signature: (JIIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniExperimentalFeatures_nativeEnableCustomPageSizes
  (JNIEnv *, jclass, jlong, jint, jint, jboolean);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniExperimentalFeatures
 * Method:    nativeGetFeatureSupport
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniExperimentalFeatures_nativeGetFeatureSupport
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
