/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniFunction */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniFunction
#define _Included_ai_tegmentum_wasmtime4j_jni_JniFunction
#ifdef __cplusplus
extern "C" {
#endif
#undef ai_tegmentum_wasmtime4j_jni_JniFunction_MAX_CACHE_SIZE
#define ai_tegmentum_wasmtime4j_jni_JniFunction_MAX_CACHE_SIZE 100L
#undef ai_tegmentum_wasmtime4j_jni_JniFunction_OPTIMIZATION_CHECK_INTERVAL
#define ai_tegmentum_wasmtime4j_jni_JniFunction_OPTIMIZATION_CHECK_INTERVAL 1000LL
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniFunction
 * Method:    nativeGetParameterTypes
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniFunction_nativeGetParameterTypes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniFunction
 * Method:    nativeGetReturnTypes
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniFunction_nativeGetReturnTypes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniFunction
 * Method:    nativeCall
 * Signature: (J[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniFunction_nativeCall
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniFunction
 * Method:    nativeCallMultiValue
 * Signature: (J[Ljava/lang/Object;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniFunction_nativeCallMultiValue
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniFunction
 * Method:    nativeCallInt
 * Signature: (J[I)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniFunction_nativeCallInt
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniFunction
 * Method:    nativeCallLong
 * Signature: (J[J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniFunction_nativeCallLong
  (JNIEnv *, jclass, jlong, jlongArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniFunction
 * Method:    nativeCallFloat
 * Signature: (J[F)F
 */
JNIEXPORT jfloat JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniFunction_nativeCallFloat
  (JNIEnv *, jclass, jlong, jfloatArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniFunction
 * Method:    nativeCallDouble
 * Signature: (J[D)D
 */
JNIEXPORT jdouble JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniFunction_nativeCallDouble
  (JNIEnv *, jclass, jlong, jdoubleArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniFunction
 * Method:    nativeDestroyFunction
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniFunction_nativeDestroyFunction
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
