/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniModuleCache */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniModuleCache
#define _Included_ai_tegmentum_wasmtime4j_jni_JniModuleCache
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniModuleCache
 * Method:    nativeCreateWithConfig
 * Signature: (JLjava/lang/String;JIZI)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniModuleCache_nativeCreateWithConfig
  (JNIEnv *, jclass, jlong, jstring, jlong, jint, jboolean, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniModuleCache
 * Method:    nativeGetOrCompile
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniModuleCache_nativeGetOrCompile
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniModuleCache
 * Method:    nativePrecompile
 * Signature: (J[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniModuleCache_nativePrecompile
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniModuleCache
 * Method:    nativeClear
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniModuleCache_nativeClear
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniModuleCache
 * Method:    nativePerformMaintenance
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniModuleCache_nativePerformMaintenance
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniModuleCache
 * Method:    nativeEntryCount
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniModuleCache_nativeEntryCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniModuleCache
 * Method:    nativeStorageBytes
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniModuleCache_nativeStorageBytes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniModuleCache
 * Method:    nativeHitCount
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniModuleCache_nativeHitCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniModuleCache
 * Method:    nativeMissCount
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniModuleCache_nativeMissCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniModuleCache
 * Method:    nativeDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniModuleCache_nativeDestroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
