/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperationsPreview2 */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperationsPreview2
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperationsPreview2
#ifdef __cplusplus
extern "C" {
#endif
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperationsPreview2_CLOCK_REALTIME
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperationsPreview2_CLOCK_REALTIME 0L
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperationsPreview2_CLOCK_MONOTONIC
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperationsPreview2_CLOCK_MONOTONIC 1L
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperationsPreview2_CLOCK_PROCESS_CPUTIME
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperationsPreview2_CLOCK_PROCESS_CPUTIME 2L
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperationsPreview2_CLOCK_THREAD_CPUTIME
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperationsPreview2_CLOCK_THREAD_CPUTIME 3L
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperationsPreview2_NANOS_PER_SECOND
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperationsPreview2_NANOS_PER_SECOND 1000000000LL
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperationsPreview2
 * Method:    nativeGetCurrentTime
 * Signature: (JIJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperationsPreview2_nativeGetCurrentTime
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperationsPreview2
 * Method:    nativeGetClockResolution
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperationsPreview2_nativeGetClockResolution
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperationsPreview2
 * Method:    nativeSleep
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperationsPreview2_nativeSleep
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperationsPreview2
 * Method:    nativeCreateTimer
 * Signature: (JJ)Lai/tegmentum/wasmtime4j/jni/wasi/WasiTimeOperationsPreview2/TimerResult;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperationsPreview2_nativeCreateTimer
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperationsPreview2
 * Method:    nativeCancelTimer
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiTimeOperationsPreview2_nativeCancelTimer
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
