/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalProcess */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalProcess
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalProcess
#ifdef __cplusplus
extern "C" {
#endif
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalProcess_MAX_CONCURRENT_PROCESSES
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalProcess_MAX_CONCURRENT_PROCESSES 100L
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalProcess_MAX_MONITORING_INTERVAL_SECONDS
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalProcess_MAX_MONITORING_INTERVAL_SECONDS 3600LL
#undef ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalProcess_MAX_SHARED_MEMORY_SIZE
#define ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalProcess_MAX_SHARED_MEMORY_SIZE 268435456LL
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalProcess
 * Method:    nativeCreateSandboxedProcess
 * Signature: (JJLjava/lang/String;[Ljava/lang/String;[Ljava/lang/String;IIZZZJIIIJ)Lai/tegmentum/wasmtime4j/jni/wasi/WasiExperimentalProcess/ProcessCreationResult;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalProcess_nativeCreateSandboxedProcess
  (JNIEnv *, jclass, jlong, jlong, jstring, jobjectArray, jobjectArray, jint, jint, jboolean, jboolean, jboolean, jlong, jint, jint, jint, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalProcess
 * Method:    nativeCreateResourceMonitor
 * Signature: (JJJJJIJJZ)Lai/tegmentum/wasmtime4j/jni/wasi/WasiExperimentalProcess/ResourceMonitorResult;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalProcess_nativeCreateResourceMonitor
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jint, jlong, jlong, jboolean);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalProcess
 * Method:    nativeCreateIpcChannel
 * Signature: (JJJJIIIZZ)Lai/tegmentum/wasmtime4j/jni/wasi/WasiExperimentalProcess/IpcCreationResult;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalProcess_nativeCreateIpcChannel
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jint, jint, jboolean, jboolean);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalProcess
 * Method:    nativeRegisterSystemService
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;IZ)Lai/tegmentum/wasmtime4j/jni/wasi/WasiExperimentalProcess/ServiceRegistrationResult;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalProcess_nativeRegisterSystemService
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring, jobjectArray, jobjectArray, jint, jboolean);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalProcess
 * Method:    nativeDiscoverSystemServices
 * Signature: (JLjava/lang/String;[Ljava/lang/String;)[Lai/tegmentum/wasmtime4j/jni/wasi/WasiExperimentalProcess/ServiceDiscoveryResult;
 */
JNIEXPORT jobjectArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalProcess_nativeDiscoverSystemServices
  (JNIEnv *, jclass, jlong, jstring, jobjectArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalProcess
 * Method:    nativeGetProcessResourceUsage
 * Signature: (JJ)Lai/tegmentum/wasmtime4j/jni/wasi/WasiExperimentalProcess/ResourceUsageResult;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalProcess_nativeGetProcessResourceUsage
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalProcess
 * Method:    nativeTerminateProcess
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalProcess_nativeTerminateProcess
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalProcess
 * Method:    nativeStopResourceMonitor
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalProcess_nativeStopResourceMonitor
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalProcess
 * Method:    nativeCloseIpcChannel
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalProcess_nativeCloseIpcChannel
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalProcess
 * Method:    nativeUnregisterSystemService
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiExperimentalProcess_nativeUnregisterSystemService
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
