/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket
 * Method:    nativeCreate
 * Signature: (JZ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket_nativeCreate
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket
 * Method:    nativeStartBind
 * Signature: (JJZ[B[BIII)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket_nativeStartBind
  (JNIEnv *, jclass, jlong, jlong, jboolean, jbyteArray, jbyteArray, jint, jint, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket
 * Method:    nativeFinishBind
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket_nativeFinishBind
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket
 * Method:    nativeStartConnect
 * Signature: (JJZ[B[BIII)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket_nativeStartConnect
  (JNIEnv *, jclass, jlong, jlong, jboolean, jbyteArray, jbyteArray, jint, jint, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket
 * Method:    nativeFinishConnect
 * Signature: (JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket_nativeFinishConnect
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket
 * Method:    nativeStartListen
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket_nativeStartListen
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket
 * Method:    nativeFinishListen
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket_nativeFinishListen
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket
 * Method:    nativeAccept
 * Signature: (JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket_nativeAccept
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket
 * Method:    nativeLocalAddress
 * Signature: (JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket_nativeLocalAddress
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket
 * Method:    nativeRemoteAddress
 * Signature: (JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket_nativeRemoteAddress
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket
 * Method:    nativeAddressFamily
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket_nativeAddressFamily
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket
 * Method:    nativeSetListenBacklogSize
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket_nativeSetListenBacklogSize
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket
 * Method:    nativeSetKeepAliveEnabled
 * Signature: (JJZ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket_nativeSetKeepAliveEnabled
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket
 * Method:    nativeSetKeepAliveIdleTime
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket_nativeSetKeepAliveIdleTime
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket
 * Method:    nativeSetKeepAliveInterval
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket_nativeSetKeepAliveInterval
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket
 * Method:    nativeSetKeepAliveCount
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket_nativeSetKeepAliveCount
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket
 * Method:    nativeSetHopLimit
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket_nativeSetHopLimit
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket
 * Method:    nativeReceiveBufferSize
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket_nativeReceiveBufferSize
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket
 * Method:    nativeSetReceiveBufferSize
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket_nativeSetReceiveBufferSize
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket
 * Method:    nativeSendBufferSize
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket_nativeSendBufferSize
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket
 * Method:    nativeSetSendBufferSize
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket_nativeSetSendBufferSize
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket
 * Method:    nativeSubscribe
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket_nativeSubscribe
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket
 * Method:    nativeShutdown
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket_nativeShutdown
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket
 * Method:    nativeClose
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_sockets_JniWasiTcpSocket_nativeClose
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
