/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_JniComponent */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_JniComponent
#define _Included_ai_tegmentum_wasmtime4j_jni_JniComponent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeCreateComponentEngine
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeCreateComponentEngine
  (JNIEnv *, jclass);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeLoadComponentFromBytes
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeLoadComponentFromBytes
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeInstantiateComponent
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeInstantiateComponent
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeGetComponentSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeGetComponentSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeExportsInterface
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeExportsInterface
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeImportsInterface
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeImportsInterface
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeGetActiveInstancesCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeGetActiveInstancesCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeCleanupInstances
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeCleanupInstances
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeDestroyComponentEngine
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeDestroyComponentEngine
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeDestroyComponent
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeDestroyComponent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeDestroyComponentInstance
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeDestroyComponentInstance
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeCompileComponentWat
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeCompileComponentWat
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeGetComponentExportCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeGetComponentExportCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeGetComponentImportCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeGetComponentImportCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeGetComponentExportName
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeGetComponentExportName
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeGetComponentImportName
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeGetComponentImportName
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeComponentHasExport
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeComponentHasExport
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeComponentHasImport
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeComponentHasImport
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeComponentValidate
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeComponentValidate
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeSerializeComponent
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeSerializeComponent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeDeserializeComponent
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeDeserializeComponent
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeDeserializeComponentFile
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeDeserializeComponentFile
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeGetComponentResourcesRequired
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeGetComponentResourcesRequired
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeComponentEngineCleanupInstances
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeComponentEngineCleanupInstances
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeComponentEngineSupportsFeature
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeComponentEngineSupportsFeature
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeComponentGetExportInterface
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeComponentGetExportInterface
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeWitParserNew
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeWitParserNew
  (JNIEnv *, jclass);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeWitParserDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeWitParserDestroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeWitParserParseInterface
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeWitParserParseInterface
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeWitParserValidateSyntax
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeWitParserValidateSyntax
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeComponentInvokeFunction
 * Signature: (JJLjava/lang/String;[I[[B)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeComponentInvokeFunction
  (JNIEnv *, jclass, jlong, jlong, jstring, jintArray, jobjectArray);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeComponentInstanceHasFunc
 * Signature: (JJLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeComponentInstanceHasFunc
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeComponentInstanceGetModule
 * Signature: (JJLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeComponentInstanceGetModule
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeComponentInstanceHasResource
 * Signature: (JJLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeComponentInstanceHasResource
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeGetExportIndex
 * Signature: (JJLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeGetExportIndex
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeDestroyExportIndex
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeDestroyExportIndex
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeComponentInstanceHasFuncByIndex
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeComponentInstanceHasFuncByIndex
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeRunConcurrentCalls
 * Signature: (JJLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeRunConcurrentCalls
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeGetFullComponentTypeJson
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeGetFullComponentTypeJson
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_JniComponent
 * Method:    nativeGetSubstitutedComponentTypeJson
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_tegmentum_wasmtime4j_jni_JniComponent_nativeGetSubstitutedComponentTypeJson
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
