/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_WasiContext */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_WasiContext
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_WasiContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiContext
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiContext_nativeClose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_WasiContext
 * Method:    nativeCreate
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_WasiContext_nativeCreate
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jobjectArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
