/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_tegmentum_wasmtime4j_jni_wasi_clocks_JniWasiTimezone */

#ifndef _Included_ai_tegmentum_wasmtime4j_jni_wasi_clocks_JniWasiTimezone
#define _Included_ai_tegmentum_wasmtime4j_jni_wasi_clocks_JniWasiTimezone
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_clocks_JniWasiTimezone
 * Method:    nativeDisplay
 * Signature: (JJI)Lai/tegmentum/wasmtime4j/wasi/clocks/TimezoneDisplay;
 */
JNIEXPORT jobject JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_clocks_JniWasiTimezone_nativeDisplay
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     ai_tegmentum_wasmtime4j_jni_wasi_clocks_JniWasiTimezone
 * Method:    nativeUtcOffset
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_ai_tegmentum_wasmtime4j_jni_wasi_clocks_JniWasiTimezone_nativeUtcOffset
  (JNIEnv *, jclass, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
